# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fit.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_fit(object):
    def setupUi(self, fit):
        fit.setObjectName("fit")
        fit.resize(352, 498)
        fit.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.buttonBox = QtWidgets.QDialogButtonBox(fit)
        self.buttonBox.setGeometry(QtCore.QRect(10, 460, 331, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.frame = QtWidgets.QFrame(fit)
        self.frame.setGeometry(QtCore.QRect(10, 10, 331, 121))
        self.frame.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.531, cy:0.664773, radius:2, fx:1, fy:1, stop:0 rgb(0, 0, 255), stop:1 rgb(0, 0, 0));")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.CB_M = QtWidgets.QDoubleSpinBox(self.frame)
        self.CB_M.setGeometry(QtCore.QRect(110, 90, 91, 24))
        self.CB_M.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CB_M.setObjectName("CB_M")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 0, 301, 31))
        self.label.setStyleSheet("background-color: a(0);")
        self.label.setObjectName("label")
        self.CA_M = QtWidgets.QDoubleSpinBox(self.frame)
        self.CA_M.setGeometry(QtCore.QRect(110, 60, 91, 24))
        self.CA_M.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CA_M.setObjectName("CA_M")
        self.CA = QtWidgets.QCheckBox(self.frame)
        self.CA.setGeometry(QtCore.QRect(10, 60, 131, 21))
        self.CA.setStyleSheet("background-color: a( 0);\n"
"color: rgb(255, 170, 255);")
        self.CA.setChecked(True)
        self.CA.setObjectName("CA")
        self.CB = QtWidgets.QCheckBox(self.frame)
        self.CB.setGeometry(QtCore.QRect(10, 90, 131, 21))
        self.CB.setStyleSheet("background-color: a( 0);\n"
"color: rgb(255, 170, 255);")
        self.CB.setChecked(True)
        self.CB.setObjectName("CB")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(110, 30, 91, 21))
        self.label_2.setStyleSheet("background-color: a(0);\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(210, 30, 101, 21))
        self.label_5.setStyleSheet("background-color: a(0);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(10, 30, 91, 21))
        self.label_6.setStyleSheet("background-color: a(0);")
        self.label_6.setObjectName("label_6")
        self.CA_I = QtWidgets.QDoubleSpinBox(self.frame)
        self.CA_I.setGeometry(QtCore.QRect(210, 60, 101, 24))
        self.CA_I.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CA_I.setObjectName("CA_I")
        self.CB_I = QtWidgets.QDoubleSpinBox(self.frame)
        self.CB_I.setGeometry(QtCore.QRect(210, 90, 101, 24))
        self.CB_I.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CB_I.setObjectName("CB_I")
        self.frame_2 = QtWidgets.QFrame(fit)
        self.frame_2.setGeometry(QtCore.QRect(10, 140, 331, 311))
        self.frame_2.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.531, cy:0.664773, radius:2, fx:1, fy:1, stop:0 rgb(0, 0, 255), stop:1 rgb(0, 0, 0));")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.D2_M = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.D2_M.setGeometry(QtCore.QRect(110, 100, 91, 24))
        self.D2_M.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.D2_M.setObjectName("D2_M")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 311, 31))
        self.label_4.setStyleSheet("background-color: a(0);")
        self.label_4.setObjectName("label_4")
        self.D1_M = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.D1_M.setGeometry(QtCore.QRect(110, 70, 91, 24))
        self.D1_M.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.D1_M.setObjectName("D1_M")
        self.D4_M = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.D4_M.setGeometry(QtCore.QRect(110, 160, 91, 24))
        self.D4_M.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.D4_M.setObjectName("D4_M")
        self.C5_M = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.C5_M.setGeometry(QtCore.QRect(110, 190, 91, 24))
        self.C5_M.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.C5_M.setObjectName("C5_M")
        self.C6_M = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.C6_M.setGeometry(QtCore.QRect(110, 220, 91, 24))
        self.C6_M.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.C6_M.setObjectName("C6_M")
        self.D3_M = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.D3_M.setGeometry(QtCore.QRect(110, 130, 91, 24))
        self.D3_M.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.D3_M.setObjectName("D3_M")
        self.D1 = QtWidgets.QCheckBox(self.frame_2)
        self.D1.setEnabled(True)
        self.D1.setGeometry(QtCore.QRect(10, 70, 131, 21))
        self.D1.setStyleSheet("background-color: a( 0);\n"
"color: rgb(85, 0, 127);")
        self.D1.setChecked(True)
        self.D1.setObjectName("D1")
        self.C6 = QtWidgets.QCheckBox(self.frame_2)
        self.C6.setGeometry(QtCore.QRect(10, 220, 131, 21))
        self.C6.setStyleSheet("background-color: a( 0);\n"
"color: rgb(85, 85, 255);")
        self.C6.setChecked(True)
        self.C6.setObjectName("C6")
        self.C5 = QtWidgets.QCheckBox(self.frame_2)
        self.C5.setGeometry(QtCore.QRect(10, 190, 131, 21))
        self.C5.setStyleSheet("background-color: a( 0);\n"
"color: rgb(85, 85, 255);")
        self.C5.setChecked(True)
        self.C5.setObjectName("C5")
        self.D4 = QtWidgets.QCheckBox(self.frame_2)
        self.D4.setGeometry(QtCore.QRect(10, 160, 131, 21))
        self.D4.setStyleSheet("background-color: a( 0);\n"
"color: rgb(85, 85, 255);")
        self.D4.setChecked(True)
        self.D4.setObjectName("D4")
        self.D3 = QtWidgets.QCheckBox(self.frame_2)
        self.D3.setGeometry(QtCore.QRect(10, 130, 131, 21))
        self.D3.setStyleSheet("background-color: a( 0);\n"
"color: rgb(85, 85, 255);")
        self.D3.setChecked(True)
        self.D3.setObjectName("D3")
        self.D2 = QtWidgets.QCheckBox(self.frame_2)
        self.D2.setEnabled(True)
        self.D2.setGeometry(QtCore.QRect(10, 100, 131, 21))
        self.D2.setStyleSheet("background-color: a( 0);color: rgb(85, 85, 255);\n"
"")
        self.D2.setChecked(True)
        self.D2.setObjectName("D2")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(10, 40, 91, 21))
        self.label_7.setStyleSheet("background-color: a(0);")
        self.label_7.setObjectName("label_7")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(110, 40, 91, 21))
        self.label_3.setStyleSheet("background-color: a(0);")
        self.label_3.setObjectName("label_3")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(210, 40, 101, 21))
        self.label_8.setStyleSheet("background-color: a(0);")
        self.label_8.setObjectName("label_8")
        self.D1_I = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.D1_I.setGeometry(QtCore.QRect(210, 70, 101, 24))
        self.D1_I.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.D1_I.setObjectName("D1_I")
        self.D2_I = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.D2_I.setGeometry(QtCore.QRect(210, 100, 101, 24))
        self.D2_I.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.D2_I.setObjectName("D2_I")
        self.D3_I = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.D3_I.setGeometry(QtCore.QRect(210, 130, 101, 24))
        self.D3_I.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.D3_I.setObjectName("D3_I")
        self.D4_I = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.D4_I.setGeometry(QtCore.QRect(210, 160, 101, 24))
        self.D4_I.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.D4_I.setObjectName("D4_I")
        self.C5_I = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.C5_I.setGeometry(QtCore.QRect(210, 190, 101, 24))
        self.C5_I.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.C5_I.setObjectName("C5_I")
        self.C6_I = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.C6_I.setGeometry(QtCore.QRect(210, 220, 101, 24))
        self.C6_I.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.C6_I.setObjectName("C6_I")
        self.S7 = QtWidgets.QCheckBox(self.frame_2)
        self.S7.setGeometry(QtCore.QRect(10, 250, 131, 21))
        self.S7.setStyleSheet("background-color: a( 0);\n"
"color: rgb(85, 85, 255);")
        self.S7.setChecked(True)
        self.S7.setObjectName("S7")
        self.S8 = QtWidgets.QCheckBox(self.frame_2)
        self.S8.setGeometry(QtCore.QRect(10, 280, 131, 21))
        self.S8.setStyleSheet("background-color: a( 0);\n"
"color: rgb(85, 85, 255);")
        self.S8.setChecked(True)
        self.S8.setObjectName("S8")
        self.S7_M = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.S7_M.setGeometry(QtCore.QRect(110, 250, 91, 24))
        self.S7_M.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.S7_M.setObjectName("S7_M")
        self.S8_M = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.S8_M.setGeometry(QtCore.QRect(110, 280, 91, 24))
        self.S8_M.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.S8_M.setObjectName("S8_M")
        self.S7_I = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.S7_I.setGeometry(QtCore.QRect(210, 250, 101, 24))
        self.S7_I.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.S7_I.setObjectName("S7_I")
        self.S8_I = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.S8_I.setGeometry(QtCore.QRect(210, 280, 101, 24))
        self.S8_I.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.S8_I.setObjectName("S8_I")
        self.frame.raise_()
        self.buttonBox.raise_()
        self.frame_2.raise_()

        self.retranslateUi(fit)
        self.buttonBox.accepted.connect(fit.accept)
        self.buttonBox.rejected.connect(fit.reject)
        QtCore.QMetaObject.connectSlotsByName(fit)

    def retranslateUi(self, fit):
        _translate = QtCore.QCoreApplication.translate
        fit.setWindowTitle(_translate("fit", "Dialog"))
        self.label.setText(_translate("fit", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">Temperature Control 335</span></p></body></html>"))
        self.CA.setText(_translate("fit", "Cernox A"))
        self.CB.setText(_translate("fit", "Cernox B"))
        self.label_2.setText(_translate("fit", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffff7f;\">Slope</span></p></body></html>"))
        self.label_5.setText(_translate("fit", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#aaff7f;\">Intercept</span></p></body></html>"))
        self.label_6.setText(_translate("fit", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffff7f;\">Sensor</span></p></body></html>"))
        self.label_4.setText(_translate("fit", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">Temperature Monitor 218</span></p></body></html>"))
        self.D1.setText(_translate("fit", "Diodo 1"))
        self.C6.setText(_translate("fit", "Cernox 6"))
        self.C5.setText(_translate("fit", "Cernox 5"))
        self.D4.setText(_translate("fit", "Diodo 4"))
        self.D3.setText(_translate("fit", "Diodo 3"))
        self.D2.setText(_translate("fit", "Diodo 2"))
        self.label_7.setText(_translate("fit", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffff7f;\">Sensor</span></p></body></html>"))
        self.label_3.setText(_translate("fit", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffff7f;\">Slope</span></p></body></html>"))
        self.label_8.setText(_translate("fit", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffff7f;\">Intercept</span></p></body></html>"))
        self.S7.setText(_translate("fit", "None"))
        self.S8.setText(_translate("fit", "None"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    fit = QtWidgets.QDialog()
    ui = Ui_fit()
    ui.setupUi(fit)
    fit.show()
    sys.exit(app.exec_())

