# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fit.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_fit(object):
    def setupUi(self, fit):
        fit.setObjectName("fit")
        fit.resize(352, 424)
        fit.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.buttonBox = QtWidgets.QDialogButtonBox(fit)
        self.buttonBox.setGeometry(QtCore.QRect(10, 380, 331, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.frame = QtWidgets.QFrame(fit)
        self.frame.setGeometry(QtCore.QRect(10, 10, 331, 111))
        self.frame.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.531, cy:0.664773, radius:2, fx:1, fy:1, stop:0 rgba(0,0, 255, 255), stop:1 rgba(0, 255, 0, 255));")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.CB = QtWidgets.QDoubleSpinBox(self.frame)
        self.CB.setGeometry(QtCore.QRect(140, 80, 151, 24))
        self.CB.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CB.setObjectName("CB")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 10, 301, 31))
        self.label.setStyleSheet("background-color: a(0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 91, 21))
        self.label_2.setStyleSheet("background-color: a(0);")
        self.label_2.setObjectName("label_2")
        self.CA = QtWidgets.QDoubleSpinBox(self.frame)
        self.CA.setGeometry(QtCore.QRect(140, 50, 151, 24))
        self.CA.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CA.setObjectName("CA")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(30, 80, 91, 21))
        self.label_3.setStyleSheet("background-color: a(0);")
        self.label_3.setObjectName("label_3")
        self.frame_2 = QtWidgets.QFrame(fit)
        self.frame_2.setGeometry(QtCore.QRect(10, 130, 331, 241))
        self.frame_2.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.531, cy:0.664773, radius:2, fx:1, fy:1, stop:0 rgba(0,0, 255, 255), stop:1 rgba(0, 255, 0, 255));")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.D2 = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.D2.setGeometry(QtCore.QRect(140, 80, 151, 24))
        self.D2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.D2.setObjectName("D2")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 301, 31))
        self.label_4.setStyleSheet("background-color: a(0);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(30, 50, 91, 21))
        self.label_5.setStyleSheet("background-color: a(0);")
        self.label_5.setObjectName("label_5")
        self.D1 = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.D1.setGeometry(QtCore.QRect(140, 50, 151, 24))
        self.D1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.D1.setObjectName("D1")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(30, 80, 91, 21))
        self.label_6.setStyleSheet("background-color: a(0);")
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(30, 110, 91, 21))
        self.label_8.setStyleSheet("background-color: a(0);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(30, 140, 91, 21))
        self.label_9.setStyleSheet("background-color: a(0);")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(30, 170, 91, 21))
        self.label_10.setStyleSheet("background-color: a(0);")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(30, 200, 91, 21))
        self.label_11.setStyleSheet("background-color: a(0);")
        self.label_11.setObjectName("label_11")
        self.D4 = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.D4.setGeometry(QtCore.QRect(140, 140, 151, 24))
        self.D4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.D4.setObjectName("D4")
        self.C5 = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.C5.setGeometry(QtCore.QRect(140, 170, 151, 24))
        self.C5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.C5.setObjectName("C5")
        self.C6 = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.C6.setGeometry(QtCore.QRect(140, 200, 151, 24))
        self.C6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.C6.setObjectName("C6")
        self.D3 = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.D3.setGeometry(QtCore.QRect(140, 110, 151, 24))
        self.D3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.D3.setObjectName("D3")
        self.frame.raise_()
        self.buttonBox.raise_()
        self.frame_2.raise_()

        self.retranslateUi(fit)
        self.buttonBox.accepted.connect(fit.accept)
        self.buttonBox.rejected.connect(fit.reject)
        QtCore.QMetaObject.connectSlotsByName(fit)

    def retranslateUi(self, fit):
        _translate = QtCore.QCoreApplication.translate
        fit.setWindowTitle(_translate("fit", "Dialog"))
        self.label.setText(_translate("fit", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">Temperature Control 335</span></p></body></html>"))
        self.label_2.setText(_translate("fit", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">Cernox A:</span></p></body></html>"))
        self.label_3.setText(_translate("fit", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">Cernox B:</span></p></body></html>"))
        self.label_4.setText(_translate("fit", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">Temperature Monitor 218</span></p></body></html>"))
        self.label_5.setText(_translate("fit", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">Diodo 1:</span></p></body></html>"))
        self.label_6.setText(_translate("fit", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">Diodo 2:</span></p></body></html>"))
        self.label_8.setText(_translate("fit", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">Diodo 3:</span></p></body></html>"))
        self.label_9.setText(_translate("fit", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">Diodo 4:</span></p></body></html>"))
        self.label_10.setText(_translate("fit", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">Cernox 5:</span></p></body></html>"))
        self.label_11.setText(_translate("fit", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">Cernox 6:</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    fit = QtWidgets.QDialog()
    ui = Ui_fit()
    ui.setupUi(fit)
    fit.show()
    sys.exit(app.exec_())

