# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prueba1.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1237, 964)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(-40, 0, 1301, 921))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.gridLayoutWidget)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 1297, 917))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_3.setGeometry(QtCore.QRect(230, 10, 111, 25))
        self.label_3.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.linePatch = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        self.linePatch.setEnabled(False)
        self.linePatch.setGeometry(QtCore.QRect(340, 10, 621, 23))
        self.linePatch.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.linePatch.setObjectName("linePatch")
        self.directorio = QtWidgets.QToolButton(self.scrollAreaWidgetContents_4)
        self.directorio.setGeometry(QtCore.QRect(970, 10, 28, 22))
        self.directorio.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.directorio.setStyleSheet("background-color: rgb(166, 166, 166);")
        self.directorio.setObjectName("directorio")
        self.plotofdata = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.plotofdata.setEnabled(True)
        self.plotofdata.setGeometry(QtCore.QRect(50, 40, 741, 261))
        self.plotofdata.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.plotofdata.setToolTip("")
        self.plotofdata.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.531, cy:0.664773, radius:2, fx:1, fy:1, stop:0 rgba(40, 0, 78, 255), stop:1 rgba(255, 255, 255, 255));\n"
"")
        self.plotofdata.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plotofdata.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plotofdata.setObjectName("plotofdata")
        self.frame = QtWidgets.QFrame(self.plotofdata)
        self.frame.setGeometry(QtCore.QRect(10, 160, 201, 91))
        self.frame.setStyleSheet("\n"
"font: 11pt \"Sans Serif\";")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setGeometry(QtCore.QRect(10, 9, 181, 71))
        self.frame_7.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.frame_9 = QtWidgets.QFrame(self.frame_7)
        self.frame_9.setGeometry(QtCore.QRect(0, 0, 181, 21))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.Type = QtWidgets.QLabel(self.frame_9)
        self.Type.setEnabled(False)
        self.Type.setGeometry(QtCore.QRect(0, 0, 181, 21))
        self.Type.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.Type.setObjectName("Type")
        self.grafica2 = QtWidgets.QRadioButton(self.frame_7)
        self.grafica2.setEnabled(False)
        self.grafica2.setGeometry(QtCore.QRect(10, 20, 161, 24))
        self.grafica2.setStyleSheet("background-color: a(0);\n"
"font: 11pt \"Sans Serif\";")
        self.grafica2.setChecked(True)
        self.grafica2.setObjectName("grafica2")
        self.grafica1 = QtWidgets.QRadioButton(self.frame_7)
        self.grafica1.setEnabled(False)
        self.grafica1.setGeometry(QtCore.QRect(10, 40, 171, 24))
        self.grafica1.setStyleSheet("background-color: a(0);")
        self.grafica1.setChecked(False)
        self.grafica1.setObjectName("grafica1")
        self.frame_2 = QtWidgets.QFrame(self.plotofdata)
        self.frame_2.setGeometry(QtCore.QRect(10, 30, 271, 121))
        self.frame_2.setStyleSheet("\n"
"font: 11pt \"Sans Serif\";")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setGeometry(QtCore.QRect(10, 10, 251, 101))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.frame_4 = QtWidgets.QFrame(self.frame_6)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 251, 21))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.Time = QtWidgets.QLabel(self.frame_4)
        self.Time.setEnabled(False)
        self.Time.setGeometry(QtCore.QRect(0, 0, 251, 20))
        self.Time.setStyleSheet("\n"
"border: 0px solid black;\n"
"background-color: rgba(0, 0, 0, 0);")
        self.Time.setObjectName("Time")
        self.radioButton = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton.setEnabled(False)
        self.radioButton.setGeometry(QtCore.QRect(10, 30, 221, 21))
        self.radioButton.setStyleSheet("background-color: a(0);")
        self.radioButton.setObjectName("radioButton")
        self.hh = QtWidgets.QSpinBox(self.frame_6)
        self.hh.setEnabled(False)
        self.hh.setGeometry(QtCore.QRect(90, 30, 51, 21))
        self.hh.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.hh.setObjectName("hh")
        self.mm = QtWidgets.QSpinBox(self.frame_6)
        self.mm.setEnabled(False)
        self.mm.setGeometry(QtCore.QRect(150, 30, 41, 21))
        self.mm.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.mm.setObjectName("mm")
        self.ss = QtWidgets.QSpinBox(self.frame_6)
        self.ss.setEnabled(False)
        self.ss.setGeometry(QtCore.QRect(200, 30, 41, 21))
        self.ss.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ss.setObjectName("ss")
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_2.setEnabled(False)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 60, 251, 21))
        self.radioButton_2.setStyleSheet("background-color: a(0);")
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.ss.raise_()
        self.frame_4.raise_()
        self.radioButton.raise_()
        self.hh.raise_()
        self.mm.raise_()
        self.radioButton_2.raise_()
        self.pushButton = QtWidgets.QPushButton(self.plotofdata)
        self.pushButton.setEnabled(False)
        self.pushButton.setGeometry(QtCore.QRect(220, 170, 131, 31))
        self.pushButton.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"font: 12pt \"Sans Serif\";")
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.plotofdata)
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QtCore.QRect(300, 0, 191, 31))
        self.label_4.setStyleSheet("background-color: a(0);")
        self.label_4.setObjectName("label_4")
        self.frame_11 = QtWidgets.QFrame(self.plotofdata)
        self.frame_11.setGeometry(QtCore.QRect(290, 30, 191, 121))
        self.frame_11.setStyleSheet("border: 1px solid black;\n"
"font: 11pt \"Sans Serif\";")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.SetPoint1 = QtWidgets.QCheckBox(self.frame_11)
        self.SetPoint1.setEnabled(False)
        self.SetPoint1.setGeometry(QtCore.QRect(10, 50, 171, 21))
        self.SetPoint1.setStyleSheet("background-color: a(0);")
        self.SetPoint1.setObjectName("SetPoint1")
        self.heater2 = QtWidgets.QCheckBox(self.frame_11)
        self.heater2.setEnabled(False)
        self.heater2.setGeometry(QtCore.QRect(10, 70, 171, 21))
        self.heater2.setStyleSheet("background-color: a(0);")
        self.heater2.setObjectName("heater2")
        self.heater1 = QtWidgets.QCheckBox(self.frame_11)
        self.heater1.setEnabled(False)
        self.heater1.setGeometry(QtCore.QRect(10, 30, 171, 21))
        self.heater1.setStyleSheet("background-color: a(90);\n"
"alternate-background-color: rgb(85, 255, 127);")
        self.heater1.setObjectName("heater1")
        self.SetPoint2 = QtWidgets.QCheckBox(self.frame_11)
        self.SetPoint2.setEnabled(False)
        self.SetPoint2.setGeometry(QtCore.QRect(10, 90, 171, 21))
        self.SetPoint2.setStyleSheet("background-color: a(0);")
        self.SetPoint2.setObjectName("SetPoint2")
        self.graph_heater_la = QtWidgets.QLabel(self.frame_11)
        self.graph_heater_la.setEnabled(False)
        self.graph_heater_la.setGeometry(QtCore.QRect(10, 10, 101, 20))
        self.graph_heater_la.setStyleSheet("")
        self.graph_heater_la.setObjectName("graph_heater_la")
        self.color_heater = QtWidgets.QLabel(self.frame_11)
        self.color_heater.setEnabled(False)
        self.color_heater.setGeometry(QtCore.QRect(110, 10, 71, 20))
        self.color_heater.setStyleSheet("")
        self.color_heater.setObjectName("color_heater")
        self.color_H1 = QtWidgets.QPushButton(self.frame_11)
        self.color_H1.setEnabled(False)
        self.color_H1.setGeometry(QtCore.QRect(130, 30, 31, 21))
        self.color_H1.setText("")
        self.color_H1.setObjectName("color_H1")
        self.color_S1 = QtWidgets.QPushButton(self.frame_11)
        self.color_S1.setEnabled(False)
        self.color_S1.setGeometry(QtCore.QRect(130, 50, 31, 21))
        self.color_S1.setText("")
        self.color_S1.setObjectName("color_S1")
        self.color_H2 = QtWidgets.QPushButton(self.frame_11)
        self.color_H2.setEnabled(False)
        self.color_H2.setGeometry(QtCore.QRect(130, 70, 31, 21))
        self.color_H2.setText("")
        self.color_H2.setObjectName("color_H2")
        self.color_S2 = QtWidgets.QPushButton(self.frame_11)
        self.color_S2.setEnabled(False)
        self.color_S2.setGeometry(QtCore.QRect(130, 90, 31, 21))
        self.color_S2.setText("")
        self.color_S2.setObjectName("color_S2")
        self.see_ramp = QtWidgets.QPushButton(self.plotofdata)
        self.see_ramp.setEnabled(False)
        self.see_ramp.setGeometry(QtCore.QRect(220, 210, 151, 31))
        self.see_ramp.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 12pt \"Sans Serif\";\n"
"selection-background-color: rgb(255, 255, 0);")
        self.see_ramp.setObjectName("see_ramp")
        self.update_graph = QtWidgets.QPushButton(self.plotofdata)
        self.update_graph.setEnabled(False)
        self.update_graph.setGeometry(QtCore.QRect(360, 170, 121, 31))
        self.update_graph.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"font: 12pt \"Sans Serif\";")
        self.update_graph.setObjectName("update_graph")
        self.ramp = QtWidgets.QPushButton(self.plotofdata)
        self.ramp.setEnabled(False)
        self.ramp.setGeometry(QtCore.QRect(380, 210, 101, 31))
        self.ramp.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"font: 12pt \"Sans Serif\";")
        self.ramp.setObjectName("ramp")
        self.frame_3 = QtWidgets.QFrame(self.plotofdata)
        self.frame_3.setGeometry(QtCore.QRect(490, 30, 241, 221))
        self.frame_3.setStyleSheet("border: 1px solid black;\n"
"font: 11pt \"Sans Serif\";")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.Todos = QtWidgets.QCheckBox(self.frame_3)
        self.Todos.setEnabled(False)
        self.Todos.setGeometry(QtCore.QRect(10, 31, 221, 20))
        self.Todos.setStyleSheet("background-color: a(0);")
        self.Todos.setChecked(True)
        self.Todos.setObjectName("Todos")
        self.CA = QtWidgets.QCheckBox(self.frame_3)
        self.CA.setEnabled(False)
        self.CA.setGeometry(QtCore.QRect(20, 50, 211, 21))
        self.CA.setStyleSheet("background-color: a(0);\n"
"")
        self.CA.setChecked(True)
        self.CA.setObjectName("CA")
        self.CB = QtWidgets.QCheckBox(self.frame_3)
        self.CB.setEnabled(False)
        self.CB.setGeometry(QtCore.QRect(20, 70, 211, 21))
        self.CB.setStyleSheet("background-color: a(0);")
        self.CB.setChecked(True)
        self.CB.setObjectName("CB")
        self.D1 = QtWidgets.QCheckBox(self.frame_3)
        self.D1.setEnabled(False)
        self.D1.setGeometry(QtCore.QRect(20, 90, 211, 21))
        self.D1.setStyleSheet("background-color: a(0);")
        self.D1.setChecked(True)
        self.D1.setObjectName("D1")
        self.D2 = QtWidgets.QCheckBox(self.frame_3)
        self.D2.setEnabled(False)
        self.D2.setGeometry(QtCore.QRect(20, 110, 211, 21))
        self.D2.setStyleSheet("background-color: a(0);")
        self.D2.setChecked(True)
        self.D2.setObjectName("D2")
        self.D3 = QtWidgets.QCheckBox(self.frame_3)
        self.D3.setEnabled(False)
        self.D3.setGeometry(QtCore.QRect(20, 130, 211, 21))
        self.D3.setStyleSheet("background-color: a(0);")
        self.D3.setChecked(True)
        self.D3.setObjectName("D3")
        self.D4 = QtWidgets.QCheckBox(self.frame_3)
        self.D4.setEnabled(False)
        self.D4.setGeometry(QtCore.QRect(20, 150, 211, 21))
        self.D4.setStyleSheet("background-color: a(0);")
        self.D4.setChecked(True)
        self.D4.setObjectName("D4")
        self.C5 = QtWidgets.QCheckBox(self.frame_3)
        self.C5.setEnabled(False)
        self.C5.setGeometry(QtCore.QRect(20, 170, 211, 21))
        self.C5.setStyleSheet("background-color: a(0);")
        self.C5.setChecked(True)
        self.C5.setObjectName("C5")
        self.C6 = QtWidgets.QCheckBox(self.frame_3)
        self.C6.setEnabled(False)
        self.C6.setGeometry(QtCore.QRect(20, 190, 211, 21))
        self.C6.setStyleSheet("background-color: a(0);")
        self.C6.setChecked(True)
        self.C6.setObjectName("C6")
        self.ramp_CA = QtWidgets.QCheckBox(self.frame_3)
        self.ramp_CA.setEnabled(False)
        self.ramp_CA.setGeometry(QtCore.QRect(190, 50, 16, 21))
        self.ramp_CA.setStyleSheet("background-color: a(0);\n"
"")
        self.ramp_CA.setText("")
        self.ramp_CA.setObjectName("ramp_CA")
        self.ramp_C5 = QtWidgets.QCheckBox(self.frame_3)
        self.ramp_C5.setGeometry(QtCore.QRect(190, 170, 16, 21))
        self.ramp_C5.setStyleSheet("background-color: a(0);")
        self.ramp_C5.setText("")
        self.ramp_C5.setObjectName("ramp_C5")
        self.ramp_D1 = QtWidgets.QCheckBox(self.frame_3)
        self.ramp_D1.setGeometry(QtCore.QRect(190, 90, 16, 21))
        self.ramp_D1.setStyleSheet("background-color: a(0);")
        self.ramp_D1.setText("")
        self.ramp_D1.setObjectName("ramp_D1")
        self.ramp_C6 = QtWidgets.QCheckBox(self.frame_3)
        self.ramp_C6.setGeometry(QtCore.QRect(190, 190, 16, 21))
        self.ramp_C6.setStyleSheet("background-color: a(0);")
        self.ramp_C6.setText("")
        self.ramp_C6.setObjectName("ramp_C6")
        self.ramp_D4 = QtWidgets.QCheckBox(self.frame_3)
        self.ramp_D4.setGeometry(QtCore.QRect(190, 150, 16, 21))
        self.ramp_D4.setStyleSheet("background-color: a(0);")
        self.ramp_D4.setText("")
        self.ramp_D4.setObjectName("ramp_D4")
        self.ramp_D3 = QtWidgets.QCheckBox(self.frame_3)
        self.ramp_D3.setGeometry(QtCore.QRect(190, 130, 16, 21))
        self.ramp_D3.setStyleSheet("background-color: a(0);")
        self.ramp_D3.setText("")
        self.ramp_D3.setObjectName("ramp_D3")
        self.ramp_D2 = QtWidgets.QCheckBox(self.frame_3)
        self.ramp_D2.setGeometry(QtCore.QRect(190, 110, 16, 21))
        self.ramp_D2.setStyleSheet("background-color: a(0);")
        self.ramp_D2.setText("")
        self.ramp_D2.setObjectName("ramp_D2")
        self.ramp_CB = QtWidgets.QCheckBox(self.frame_3)
        self.ramp_CB.setEnabled(False)
        self.ramp_CB.setGeometry(QtCore.QRect(190, 70, 16, 21))
        self.ramp_CB.setStyleSheet("background-color: a(0);")
        self.ramp_CB.setText("")
        self.ramp_CB.setObjectName("ramp_CB")
        self.ramp_la = QtWidgets.QLabel(self.frame_3)
        self.ramp_la.setEnabled(False)
        self.ramp_la.setGeometry(QtCore.QRect(160, 10, 71, 21))
        self.ramp_la.setStyleSheet("")
        self.ramp_la.setObjectName("ramp_la")
        self.color_sensor = QtWidgets.QLabel(self.frame_3)
        self.color_sensor.setEnabled(False)
        self.color_sensor.setGeometry(QtCore.QRect(100, 10, 61, 21))
        self.color_sensor.setStyleSheet("")
        self.color_sensor.setObjectName("color_sensor")
        self.graph_sensor = QtWidgets.QLabel(self.frame_3)
        self.graph_sensor.setEnabled(False)
        self.graph_sensor.setGeometry(QtCore.QRect(10, 10, 91, 21))
        self.graph_sensor.setStyleSheet("")
        self.graph_sensor.setObjectName("graph_sensor")
        self.color_CA = QtWidgets.QPushButton(self.frame_3)
        self.color_CA.setEnabled(False)
        self.color_CA.setGeometry(QtCore.QRect(120, 50, 31, 21))
        self.color_CA.setText("")
        self.color_CA.setObjectName("color_CA")
        self.color_CB = QtWidgets.QPushButton(self.frame_3)
        self.color_CB.setEnabled(False)
        self.color_CB.setGeometry(QtCore.QRect(120, 70, 31, 21))
        self.color_CB.setText("")
        self.color_CB.setObjectName("color_CB")
        self.color_D1 = QtWidgets.QPushButton(self.frame_3)
        self.color_D1.setEnabled(False)
        self.color_D1.setGeometry(QtCore.QRect(120, 90, 31, 21))
        self.color_D1.setText("")
        self.color_D1.setObjectName("color_D1")
        self.color_D2 = QtWidgets.QPushButton(self.frame_3)
        self.color_D2.setEnabled(False)
        self.color_D2.setGeometry(QtCore.QRect(120, 110, 31, 21))
        self.color_D2.setText("")
        self.color_D2.setObjectName("color_D2")
        self.color_D3 = QtWidgets.QPushButton(self.frame_3)
        self.color_D3.setEnabled(False)
        self.color_D3.setGeometry(QtCore.QRect(120, 130, 31, 21))
        self.color_D3.setText("")
        self.color_D3.setObjectName("color_D3")
        self.color_D4 = QtWidgets.QPushButton(self.frame_3)
        self.color_D4.setGeometry(QtCore.QRect(120, 150, 31, 21))
        self.color_D4.setText("")
        self.color_D4.setObjectName("color_D4")
        self.color_C5 = QtWidgets.QPushButton(self.frame_3)
        self.color_C5.setGeometry(QtCore.QRect(120, 170, 31, 21))
        self.color_C5.setText("")
        self.color_C5.setObjectName("color_C5")
        self.color_C6 = QtWidgets.QPushButton(self.frame_3)
        self.color_C6.setEnabled(False)
        self.color_C6.setGeometry(QtCore.QRect(120, 190, 31, 21))
        self.color_C6.setText("")
        self.color_C6.setObjectName("color_C6")
        self.CA.raise_()
        self.CB.raise_()
        self.D1.raise_()
        self.D2.raise_()
        self.D3.raise_()
        self.D4.raise_()
        self.C5.raise_()
        self.C6.raise_()
        self.ramp_CA.raise_()
        self.ramp_C5.raise_()
        self.ramp_D1.raise_()
        self.ramp_C6.raise_()
        self.ramp_D4.raise_()
        self.ramp_D3.raise_()
        self.ramp_D2.raise_()
        self.ramp_CB.raise_()
        self.ramp_la.raise_()
        self.Todos.raise_()
        self.color_sensor.raise_()
        self.graph_sensor.raise_()
        self.color_CA.raise_()
        self.color_CB.raise_()
        self.color_D1.raise_()
        self.color_D2.raise_()
        self.color_D3.raise_()
        self.color_D4.raise_()
        self.color_C5.raise_()
        self.color_C6.raise_()
        self.frame_2.raise_()
        self.label_4.raise_()
        self.frame.raise_()
        self.pushButton.raise_()
        self.frame_11.raise_()
        self.see_ramp.raise_()
        self.update_graph.raise_()
        self.ramp.raise_()
        self.frame_3.raise_()
        self.frame_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.frame_5.setEnabled(True)
        self.frame_5.setGeometry(QtCore.QRect(800, 40, 451, 571))
        self.frame_5.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.531, cy:0.664773, radius:2, fx:1, fy:1, stop:0 rgba(40, 0, 78, 255), stop:1 rgba(255, 255, 255, 255));")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 441, 31))
        self.label_5.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_5)
        self.scrollArea.setGeometry(QtCore.QRect(20, 50, 411, 471))
        self.scrollArea.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 11pt \"Sans Serif\";")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 409, 469))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.stop = QtWidgets.QPushButton(self.frame_5)
        self.stop.setEnabled(False)
        self.stop.setGeometry(QtCore.QRect(360, 530, 71, 23))
        self.stop.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"font: 11pt \"Sans Serif\";")
        self.stop.setObjectName("stop")
        self.start = QtWidgets.QPushButton(self.frame_5)
        self.start.setEnabled(False)
        self.start.setGeometry(QtCore.QRect(20, 530, 80, 23))
        self.start.setStyleSheet("background-color: rgb(85, 255, 0);\n"
"font: 11pt \"Sans Serif\";")
        self.start.setObjectName("start")
        self.lastdata = QtWidgets.QPushButton(self.frame_5)
        self.lastdata.setEnabled(False)
        self.lastdata.setGeometry(QtCore.QRect(110, 530, 121, 23))
        self.lastdata.setStyleSheet("font: 11pt \"Sans Serif\";\n"
"background-color: rgb(200, 212, 255);")
        self.lastdata.setObjectName("lastdata")
        self.SeeData = QtWidgets.QPushButton(self.frame_5)
        self.SeeData.setEnabled(False)
        self.SeeData.setGeometry(QtCore.QRect(250, 530, 91, 21))
        self.SeeData.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"font: 11pt \"Sans Serif\";")
        self.SeeData.setObjectName("SeeData")
        self.control = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.control.setEnabled(True)
        self.control.setGeometry(QtCore.QRect(50, 310, 741, 301))
        self.control.setToolTip("")
        self.control.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.531, cy:0.664773, radius:2, fx:1, fy:1, stop:0 rgba(40, 0, 78, 255), stop:1 rgba(255, 255, 255, 255));\n"
"")
        self.control.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.control.setFrameShadow(QtWidgets.QFrame.Raised)
        self.control.setObjectName("control")
        self.label_6 = QtWidgets.QLabel(self.control)
        self.label_6.setGeometry(QtCore.QRect(300, 0, 131, 31))
        self.label_6.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.label_6.setObjectName("label_6")
        self.heater1_2 = QtWidgets.QFrame(self.control)
        self.heater1_2.setGeometry(QtCore.QRect(10, 30, 361, 261))
        self.heater1_2.setToolTip("")
        self.heater1_2.setStyleSheet("\n"
"font: 12pt \"Sans Serif\";")
        self.heater1_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.heater1_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.heater1_2.setObjectName("heater1_2")
        self.frame_10 = QtWidgets.QFrame(self.heater1_2)
        self.frame_10.setGeometry(QtCore.QRect(10, 10, 341, 211))
        self.frame_10.setStyleSheet("font: 10pt \"Sans Serif\";")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.frame_12 = QtWidgets.QFrame(self.frame_10)
        self.frame_12.setGeometry(QtCore.QRect(0, 0, 341, 21))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.heater_1 = QtWidgets.QRadioButton(self.frame_12)
        self.heater_1.setEnabled(False)
        self.heater_1.setGeometry(QtCore.QRect(50, 0, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.heater_1.setFont(font)
        self.heater_1.setToolTip("")
        self.heater_1.setStyleSheet("font: 15pt \"Sans Serif\";\n"
"background-color: a(0);")
        self.heater_1.setObjectName("heater_1")
        self.seeStatus_1 = QtWidgets.QCheckBox(self.frame_12)
        self.seeStatus_1.setEnabled(False)
        self.seeStatus_1.setGeometry(QtCore.QRect(220, 0, 91, 20))
        self.seeStatus_1.setStyleSheet("background-color: a(0);")
        self.seeStatus_1.setObjectName("seeStatus_1")
        self.label_7 = QtWidgets.QLabel(self.frame_10)
        self.label_7.setEnabled(False)
        self.label_7.setGeometry(QtCore.QRect(160, 180, 91, 21))
        self.label_7.setStyleSheet("background-color: a(0);")
        self.label_7.setObjectName("label_7")
        self.setPoint_num_1 = QtWidgets.QDoubleSpinBox(self.frame_10)
        self.setPoint_num_1.setEnabled(False)
        self.setPoint_num_1.setGeometry(QtCore.QRect(250, 180, 81, 21))
        self.setPoint_num_1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Sans Serif\";")
        self.setPoint_num_1.setObjectName("setPoint_num_1")
        self.label_9 = QtWidgets.QLabel(self.frame_10)
        self.label_9.setEnabled(False)
        self.label_9.setGeometry(QtCore.QRect(10, 180, 81, 21))
        self.label_9.setStyleSheet("background-color: a(0);")
        self.label_9.setObjectName("label_9")
        self.ramp_1 = QtWidgets.QDoubleSpinBox(self.frame_10)
        self.ramp_1.setEnabled(False)
        self.ramp_1.setGeometry(QtCore.QRect(70, 180, 71, 21))
        self.ramp_1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ramp_1.setObjectName("ramp_1")
        self.label_10 = QtWidgets.QLabel(self.frame_10)
        self.label_10.setEnabled(False)
        self.label_10.setGeometry(QtCore.QRect(0, 40, 91, 21))
        self.label_10.setStyleSheet("background-color: a(0);")
        self.label_10.setObjectName("label_10")
        self.range_manual_1 = QtWidgets.QRadioButton(self.frame_10)
        self.range_manual_1.setEnabled(False)
        self.range_manual_1.setGeometry(QtCore.QRect(10, 100, 81, 21))
        self.range_manual_1.setStyleSheet("background-color: a(0);")
        self.range_manual_1.setObjectName("range_manual_1")
        self.range_1 = QtWidgets.QComboBox(self.frame_10)
        self.range_1.setEnabled(False)
        self.range_1.setGeometry(QtCore.QRect(20, 130, 61, 20))
        self.range_1.setStyleSheet("background-color: a(0);")
        self.range_1.setObjectName("range_1")
        self.range_1.addItem("")
        self.range_1.addItem("")
        self.range_1.addItem("")
        self.status_1 = QtWidgets.QScrollArea(self.frame_10)
        self.status_1.setEnabled(False)
        self.status_1.setGeometry(QtCore.QRect(90, 30, 241, 141))
        self.status_1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Sans Serif\";")
        self.status_1.setWidgetResizable(True)
        self.status_1.setObjectName("status_1")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 239, 139))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.status_1.setWidget(self.scrollAreaWidgetContents_2)
        self.range_automatic_1 = QtWidgets.QRadioButton(self.frame_10)
        self.range_automatic_1.setEnabled(False)
        self.range_automatic_1.setGeometry(QtCore.QRect(10, 70, 61, 21))
        self.range_automatic_1.setStyleSheet("background-color: a(0);")
        self.range_automatic_1.setChecked(True)
        self.range_automatic_1.setObjectName("range_automatic_1")
        self.Off_1 = QtWidgets.QPushButton(self.heater1_2)
        self.Off_1.setEnabled(False)
        self.Off_1.setGeometry(QtCore.QRect(210, 230, 80, 23))
        self.Off_1.setStyleSheet("background-color: rgb(162, 42, 44);")
        self.Off_1.setObjectName("Off_1")
        self.update_1 = QtWidgets.QPushButton(self.heater1_2)
        self.update_1.setEnabled(False)
        self.update_1.setGeometry(QtCore.QRect(50, 230, 80, 23))
        self.update_1.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.update_1.setObjectName("update_1")
        self.frame_8 = QtWidgets.QFrame(self.control)
        self.frame_8.setGeometry(QtCore.QRect(380, 30, 351, 261))
        self.frame_8.setToolTip("")
        self.frame_8.setStyleSheet("font: 12pt \"Sans Serif\";\n"
"")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.frame_13 = QtWidgets.QFrame(self.frame_8)
        self.frame_13.setGeometry(QtCore.QRect(10, 10, 331, 211))
        self.frame_13.setStyleSheet("font: 10pt \"Sans Serif\";")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.frame_14 = QtWidgets.QFrame(self.frame_13)
        self.frame_14.setGeometry(QtCore.QRect(0, 0, 331, 21))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.heater_2 = QtWidgets.QRadioButton(self.frame_14)
        self.heater_2.setEnabled(False)
        self.heater_2.setGeometry(QtCore.QRect(40, 0, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.heater_2.setFont(font)
        self.heater_2.setStyleSheet("font: 15pt \"Sans Serif\";\n"
"background-color: a(0);")
        self.heater_2.setObjectName("heater_2")
        self.seeStatus_2 = QtWidgets.QCheckBox(self.frame_14)
        self.seeStatus_2.setEnabled(False)
        self.seeStatus_2.setGeometry(QtCore.QRect(200, 0, 99, 21))
        self.seeStatus_2.setStyleSheet("background-color: a(0);")
        self.seeStatus_2.setObjectName("seeStatus_2")
        self.status_2 = QtWidgets.QScrollArea(self.frame_13)
        self.status_2.setEnabled(False)
        self.status_2.setGeometry(QtCore.QRect(80, 30, 241, 141))
        self.status_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.status_2.setWidgetResizable(True)
        self.status_2.setObjectName("status_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 239, 139))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.status_2.setWidget(self.scrollAreaWidgetContents_3)
        self.label_8 = QtWidgets.QLabel(self.frame_13)
        self.label_8.setEnabled(False)
        self.label_8.setGeometry(QtCore.QRect(150, 180, 91, 21))
        self.label_8.setStyleSheet("background-color: a(0);")
        self.label_8.setObjectName("label_8")
        self.label_11 = QtWidgets.QLabel(self.frame_13)
        self.label_11.setEnabled(False)
        self.label_11.setGeometry(QtCore.QRect(10, 180, 81, 21))
        self.label_11.setStyleSheet("background-color: a(0);")
        self.label_11.setObjectName("label_11")
        self.ramp_2 = QtWidgets.QDoubleSpinBox(self.frame_13)
        self.ramp_2.setEnabled(False)
        self.ramp_2.setGeometry(QtCore.QRect(70, 180, 71, 24))
        self.ramp_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ramp_2.setObjectName("ramp_2")
        self.setPoint_num_2 = QtWidgets.QDoubleSpinBox(self.frame_13)
        self.setPoint_num_2.setEnabled(False)
        self.setPoint_num_2.setGeometry(QtCore.QRect(240, 180, 81, 24))
        self.setPoint_num_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.setPoint_num_2.setObjectName("setPoint_num_2")
        self.label_12 = QtWidgets.QLabel(self.frame_13)
        self.label_12.setEnabled(False)
        self.label_12.setGeometry(QtCore.QRect(0, 40, 81, 21))
        self.label_12.setStyleSheet("background-color: a(0);")
        self.label_12.setObjectName("label_12")
        self.range_manual_2 = QtWidgets.QRadioButton(self.frame_13)
        self.range_manual_2.setEnabled(False)
        self.range_manual_2.setGeometry(QtCore.QRect(0, 100, 81, 21))
        self.range_manual_2.setStyleSheet("background-color: a(0);")
        self.range_manual_2.setObjectName("range_manual_2")
        self.range_automatic_2 = QtWidgets.QRadioButton(self.frame_13)
        self.range_automatic_2.setEnabled(False)
        self.range_automatic_2.setGeometry(QtCore.QRect(0, 70, 101, 21))
        self.range_automatic_2.setStyleSheet("background-color: a(0);")
        self.range_automatic_2.setChecked(True)
        self.range_automatic_2.setObjectName("range_automatic_2")
        self.range_2 = QtWidgets.QComboBox(self.frame_13)
        self.range_2.setEnabled(False)
        self.range_2.setGeometry(QtCore.QRect(10, 130, 61, 20))
        self.range_2.setStyleSheet("background-color: a(0);")
        self.range_2.setObjectName("range_2")
        self.range_2.addItem("")
        self.range_2.addItem("")
        self.range_2.addItem("")
        self.update_2 = QtWidgets.QPushButton(self.frame_8)
        self.update_2.setEnabled(False)
        self.update_2.setGeometry(QtCore.QRect(50, 230, 80, 23))
        self.update_2.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.update_2.setObjectName("update_2")
        self.Off_2 = QtWidgets.QPushButton(self.frame_8)
        self.Off_2.setEnabled(False)
        self.Off_2.setGeometry(QtCore.QRect(220, 230, 80, 23))
        self.Off_2.setStyleSheet("background-color: rgb(163, 0, 2);")
        self.Off_2.setObjectName("Off_2")
        self.tabWidget = QtWidgets.QTabWidget(self.scrollAreaWidgetContents_4)
        self.tabWidget.setGeometry(QtCore.QRect(50, 620, 1201, 301))
        self.tabWidget.setStyleSheet("background-color: a(0);")
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidgetPage1 = QtWidgets.QWidget()
        self.tabWidgetPage1.setObjectName("tabWidgetPage1")
        self.tabWidget.addTab(self.tabWidgetPage1, "")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_4)
        self.gridLayout.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1237, 22))
        self.menubar.setObjectName("menubar")
        self.menupl = QtWidgets.QMenu(self.menubar)
        self.menupl.setObjectName("menupl")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.actionInfo = QtWidgets.QAction(MainWindow)
        self.actionInfo.setObjectName("actionInfo")
        self.action218 = QtWidgets.QAction(MainWindow)
        self.action218.setObjectName("action218")
        self.action335 = QtWidgets.QAction(MainWindow)
        self.action335.setObjectName("action335")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout_335 = QtWidgets.QAction(MainWindow)
        self.actionAbout_335.setObjectName("actionAbout_335")
        self.actionAbout_318 = QtWidgets.QAction(MainWindow)
        self.actionAbout_318.setObjectName("actionAbout_318")
        self.menupl.addAction(self.actionInfo)
        self.menupl.addAction(self.actionHelp)
        self.menupl.addAction(self.actionAbout_335)
        self.menupl.addAction(self.actionAbout_318)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.action218)
        self.menuSettings.addAction(self.action335)
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menupl.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Address:</span></p></body></html>"))
        self.directorio.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Select folder</span></p></body></html>"))
        self.directorio.setText(_translate("MainWindow", "..."))
        self.Type.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Type</span></p></body></html>"))
        self.grafica2.setText(_translate("MainWindow", "Plot "))
        self.grafica1.setText(_translate("MainWindow", "Plot with refresh"))
        self.Time.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Time</span></p></body></html>"))
        self.radioButton.setText(_translate("MainWindow", "Period:          :        :"))
        self.radioButton_2.setText(_translate("MainWindow", "Desde el inicio de los tiempos"))
        self.pushButton.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Plot</span></p></body></html>"))
        self.pushButton.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\">Plot</p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Plot"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#ffffff;\">Plot of Data</span></p></body></html>"))
        self.frame_11.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Plot data of Heaters</span></p></body></html>"))
        self.SetPoint1.setText(_translate("MainWindow", "SetPoint 1"))
        self.heater2.setText(_translate("MainWindow", "Heater 2"))
        self.heater1.setText(_translate("MainWindow", "Heater 1"))
        self.SetPoint2.setText(_translate("MainWindow", "SetPoint 2"))
        self.graph_heater_la.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Graph</span></p></body></html>"))
        self.color_heater.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Color</span></p></body></html>"))
        self.see_ramp.setText(_translate("MainWindow", "See Plot Ramp"))
        self.update_graph.setText(_translate("MainWindow", "Update"))
        self.ramp.setText(_translate("MainWindow", "Ramp"))
        self.frame_3.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Sensors</span></p></body></html>"))
        self.Todos.setText(_translate("MainWindow", "All sensors"))
        self.CA.setText(_translate("MainWindow", "Cernox A"))
        self.CB.setText(_translate("MainWindow", "Cernox B"))
        self.D1.setText(_translate("MainWindow", "Diodo 1"))
        self.D2.setText(_translate("MainWindow", "Diodo 2"))
        self.D3.setText(_translate("MainWindow", "Diodo 3"))
        self.D4.setText(_translate("MainWindow", "Diodo 4"))
        self.C5.setText(_translate("MainWindow", "Cernox 5"))
        self.C6.setText(_translate("MainWindow", "Cernox 6"))
        self.ramp_la.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Ramp<br/></span></p></body></html>"))
        self.color_sensor.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Color</span></p></body></html>"))
        self.graph_sensor.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Graph</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#ffffff;\">Acquisition of Data</span></p></body></html>"))
        self.scrollArea.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Status</span></p></body></html>"))
        self.scrollArea.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Estado</p></body></html>"))
        self.stop.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#ffffff;\">Stop acquisition</span></p></body></html>"))
        self.stop.setText(_translate("MainWindow", "Stop"))
        self.start.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Start acquisition</span></p></body></html>"))
        self.start.setText(_translate("MainWindow", "Start"))
        self.lastdata.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">See last data</span></p></body></html>"))
        self.lastdata.setText(_translate("MainWindow", "See last data"))
        self.SeeData.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">See data</span></p></body></html>"))
        self.SeeData.setText(_translate("MainWindow", "See Data"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">Control</span></p></body></html>"))
        self.heater1_2.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Heater 1</p></body></html>"))
        self.heater_1.setText(_translate("MainWindow", "Heater 1"))
        self.seeStatus_1.setText(_translate("MainWindow", "Status"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">SetPoint:</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Ramp:</span></p><p><span style=\" font-size:11pt;\"><br/></span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Range:</span></p></body></html>"))
        self.range_manual_1.setText(_translate("MainWindow", "Manual "))
        self.range_1.setItemText(0, _translate("MainWindow", "Low"))
        self.range_1.setItemText(1, _translate("MainWindow", "Med"))
        self.range_1.setItemText(2, _translate("MainWindow", "High"))
        self.status_1.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Status Heater 1</span></p></body></html>"))
        self.range_automatic_1.setText(_translate("MainWindow", "Auto"))
        self.Off_1.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Off Heater 1</span></p></body></html>"))
        self.Off_1.setText(_translate("MainWindow", "Off"))
        self.update_1.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Update Heater 1</span></p></body></html>"))
        self.update_1.setText(_translate("MainWindow", "Update"))
        self.frame_8.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.heater_2.setText(_translate("MainWindow", "Heater 2"))
        self.seeStatus_2.setText(_translate("MainWindow", "Status"))
        self.status_2.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Status Heater 2</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Set Point:</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Ramp:</span></p><p><span style=\" font-size:11pt;\"><br/></span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Range</span>:</p></body></html>"))
        self.range_manual_2.setText(_translate("MainWindow", "Manual "))
        self.range_automatic_2.setText(_translate("MainWindow", "Auto"))
        self.range_2.setItemText(0, _translate("MainWindow", "Low"))
        self.range_2.setItemText(1, _translate("MainWindow", "Med"))
        self.range_2.setItemText(2, _translate("MainWindow", "High"))
        self.update_2.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Update Heater 2</span></p></body></html>"))
        self.update_2.setText(_translate("MainWindow", "Update"))
        self.Off_2.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#ffffff;\">Off Heater 2</span></p></body></html>"))
        self.Off_2.setText(_translate("MainWindow", "Off"))
        self.menupl.setTitle(_translate("MainWindow", "Help"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionInfo.setText(_translate("MainWindow", "Info"))
        self.action218.setText(_translate("MainWindow", "218"))
        self.action335.setText(_translate("MainWindow", "335"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionAbout_335.setText(_translate("MainWindow", "About 335"))
        self.actionAbout_318.setText(_translate("MainWindow", "About 318"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

