# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'segunda.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Segunda(object):
    def setupUi(self, Segunda):
        Segunda.setObjectName("Segunda")
        Segunda.resize(558, 335)
        self.buttonBox = QtWidgets.QDialogButtonBox(Segunda)
        self.buttonBox.setGeometry(QtCore.QRect(80, 300, 461, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.frame = QtWidgets.QFrame(Segunda)
        self.frame.setGeometry(QtCore.QRect(10, 20, 131, 61))
        self.frame.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 20, 121, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 121, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 131, 20))
        self.label_3.setObjectName("label_3")
        self.frame_2 = QtWidgets.QFrame(Segunda)
        self.frame_2.setGeometry(QtCore.QRect(10, 90, 271, 201))
        self.frame_2.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.sensor1 = QtWidgets.QCheckBox(self.frame_2)
        self.sensor1.setGeometry(QtCore.QRect(20, 30, 99, 21))
        self.sensor1.setChecked(True)
        self.sensor1.setObjectName("sensor1")
        self.sensor2 = QtWidgets.QCheckBox(self.frame_2)
        self.sensor2.setGeometry(QtCore.QRect(20, 50, 99, 21))
        self.sensor2.setChecked(True)
        self.sensor2.setObjectName("sensor2")
        self.sensor3 = QtWidgets.QCheckBox(self.frame_2)
        self.sensor3.setGeometry(QtCore.QRect(20, 70, 99, 21))
        self.sensor3.setChecked(True)
        self.sensor3.setObjectName("sensor3")
        self.sensor4 = QtWidgets.QCheckBox(self.frame_2)
        self.sensor4.setGeometry(QtCore.QRect(20, 90, 99, 21))
        self.sensor4.setChecked(True)
        self.sensor4.setObjectName("sensor4")
        self.sensor5 = QtWidgets.QCheckBox(self.frame_2)
        self.sensor5.setGeometry(QtCore.QRect(20, 110, 99, 21))
        self.sensor5.setChecked(True)
        self.sensor5.setObjectName("sensor5")
        self.sensor6 = QtWidgets.QCheckBox(self.frame_2)
        self.sensor6.setGeometry(QtCore.QRect(20, 130, 99, 21))
        self.sensor6.setChecked(True)
        self.sensor6.setObjectName("sensor6")
        self.sensor1_type = QtWidgets.QComboBox(self.frame_2)
        self.sensor1_type.setGeometry(QtCore.QRect(100, 30, 91, 23))
        self.sensor1_type.setObjectName("sensor1_type")
        self.sensor1_type.addItem("")
        self.sensor1_type.addItem("")
        self.sensor2_type = QtWidgets.QComboBox(self.frame_2)
        self.sensor2_type.setGeometry(QtCore.QRect(100, 50, 91, 23))
        self.sensor2_type.setObjectName("sensor2_type")
        self.sensor2_type.addItem("")
        self.sensor2_type.addItem("")
        self.sensor3_type = QtWidgets.QComboBox(self.frame_2)
        self.sensor3_type.setGeometry(QtCore.QRect(100, 70, 91, 23))
        self.sensor3_type.setObjectName("sensor3_type")
        self.sensor3_type.addItem("")
        self.sensor3_type.addItem("")
        self.sensor4_type = QtWidgets.QComboBox(self.frame_2)
        self.sensor4_type.setGeometry(QtCore.QRect(100, 90, 91, 23))
        self.sensor4_type.setObjectName("sensor4_type")
        self.sensor4_type.addItem("")
        self.sensor4_type.addItem("")
        self.sesnor5_type = QtWidgets.QComboBox(self.frame_2)
        self.sesnor5_type.setGeometry(QtCore.QRect(100, 110, 91, 23))
        self.sesnor5_type.setObjectName("sesnor5_type")
        self.sesnor5_type.addItem("")
        self.sesnor5_type.addItem("")
        self.sensor6_type = QtWidgets.QComboBox(self.frame_2)
        self.sensor6_type.setGeometry(QtCore.QRect(100, 130, 91, 23))
        self.sensor6_type.setObjectName("sensor6_type")
        self.sensor6_type.addItem("")
        self.sensor6_type.addItem("")
        self.sensor7_type = QtWidgets.QComboBox(self.frame_2)
        self.sensor7_type.setEnabled(False)
        self.sensor7_type.setGeometry(QtCore.QRect(100, 150, 91, 23))
        self.sensor7_type.setObjectName("sensor7_type")
        self.sensor7_type.addItem("")
        self.sensor7_type.addItem("")
        self.sensor8_type = QtWidgets.QComboBox(self.frame_2)
        self.sensor8_type.setEnabled(False)
        self.sensor8_type.setGeometry(QtCore.QRect(100, 170, 91, 23))
        self.sensor8_type.setObjectName("sensor8_type")
        self.sensor8_type.addItem("")
        self.sensor8_type.addItem("")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(106, 10, 91, 20))
        self.label_4.setObjectName("label_4")
        self.sensor7 = QtWidgets.QCheckBox(self.frame_2)
        self.sensor7.setGeometry(QtCore.QRect(20, 150, 99, 21))
        self.sensor7.setObjectName("sensor7")
        self.sensor8 = QtWidgets.QCheckBox(self.frame_2)
        self.sensor8.setGeometry(QtCore.QRect(20, 170, 99, 21))
        self.sensor8.setObjectName("sensor8")
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setGeometry(QtCore.QRect(210, 10, 61, 16))
        self.label_13.setObjectName("label_13")
        self.spinBox = QtWidgets.QSpinBox(self.frame_2)
        self.spinBox.setGeometry(QtCore.QRect(220, 30, 47, 21))
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(self.frame_2)
        self.spinBox_2.setGeometry(QtCore.QRect(220, 50, 47, 24))
        self.spinBox_2.setObjectName("spinBox_2")
        self.spinBox_3 = QtWidgets.QSpinBox(self.frame_2)
        self.spinBox_3.setGeometry(QtCore.QRect(220, 70, 47, 24))
        self.spinBox_3.setObjectName("spinBox_3")
        self.spinBox_4 = QtWidgets.QSpinBox(self.frame_2)
        self.spinBox_4.setGeometry(QtCore.QRect(220, 90, 47, 24))
        self.spinBox_4.setObjectName("spinBox_4")
        self.spinBox_5 = QtWidgets.QSpinBox(self.frame_2)
        self.spinBox_5.setGeometry(QtCore.QRect(220, 110, 47, 24))
        self.spinBox_5.setObjectName("spinBox_5")
        self.spinBox_6 = QtWidgets.QSpinBox(self.frame_2)
        self.spinBox_6.setGeometry(QtCore.QRect(220, 130, 47, 24))
        self.spinBox_6.setObjectName("spinBox_6")
        self.spinBox_7 = QtWidgets.QSpinBox(self.frame_2)
        self.spinBox_7.setEnabled(False)
        self.spinBox_7.setGeometry(QtCore.QRect(220, 150, 47, 24))
        self.spinBox_7.setObjectName("spinBox_7")
        self.spinBox_8 = QtWidgets.QSpinBox(self.frame_2)
        self.spinBox_8.setEnabled(False)
        self.spinBox_8.setGeometry(QtCore.QRect(220, 170, 47, 24))
        self.spinBox_8.setObjectName("spinBox_8")
        self.sensor8.raise_()
        self.sensor7.raise_()
        self.sensor6.raise_()
        self.sensor5.raise_()
        self.sensor4.raise_()
        self.sensor3.raise_()
        self.sensor2.raise_()
        self.sensor1.raise_()
        self.sensor1_type.raise_()
        self.sensor2_type.raise_()
        self.sensor3_type.raise_()
        self.sensor4_type.raise_()
        self.sesnor5_type.raise_()
        self.sensor6_type.raise_()
        self.sensor7_type.raise_()
        self.sensor8_type.raise_()
        self.label_4.raise_()
        self.label_13.raise_()
        self.spinBox.raise_()
        self.spinBox_2.raise_()
        self.spinBox_3.raise_()
        self.spinBox_4.raise_()
        self.spinBox_5.raise_()
        self.spinBox_6.raise_()
        self.spinBox_7.raise_()
        self.spinBox_8.raise_()
        self.frame_3 = QtWidgets.QFrame(Segunda)
        self.frame_3.setGeometry(QtCore.QRect(150, 20, 401, 61))
        self.frame_3.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(40, 0, 311, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 57, 15))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(10, 40, 57, 15))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(230, 40, 71, 16))
        self.label_8.setObjectName("label_8")
        self.root = QtWidgets.QLineEdit(self.frame_3)
        self.root.setGeometry(QtCore.QRect(40, 20, 351, 16))
        self.root.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.root.setObjectName("root")
        self.name = QtWidgets.QLineEdit(self.frame_3)
        self.name.setGeometry(QtCore.QRect(50, 40, 171, 20))
        self.name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.name.setObjectName("name")
        self.savedata = QtWidgets.QSpinBox(self.frame_3)
        self.savedata.setGeometry(QtCore.QRect(300, 40, 61, 20))
        self.savedata.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.savedata.setObjectName("savedata")
        self.frame_4 = QtWidgets.QFrame(Segunda)
        self.frame_4.setGeometry(QtCore.QRect(290, 90, 261, 91))
        self.frame_4.setStyleSheet("background-color: rgb(85, 170, 127);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_10 = QtWidgets.QLabel(self.frame_4)
        self.label_10.setGeometry(QtCore.QRect(0, 0, 251, 16))
        self.label_10.setObjectName("label_10")
        self.label_9 = QtWidgets.QLabel(self.frame_4)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 57, 15))
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.frame_4)
        self.label_11.setGeometry(QtCore.QRect(10, 40, 81, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame_4)
        self.label_12.setGeometry(QtCore.QRect(10, 60, 57, 15))
        self.label_12.setObjectName("label_12")
        self.port = QtWidgets.QLineEdit(self.frame_4)
        self.port.setGeometry(QtCore.QRect(40, 20, 211, 16))
        self.port.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.port.setObjectName("port")
        self.BaudeRade = QtWidgets.QComboBox(self.frame_4)
        self.BaudeRade.setGeometry(QtCore.QRect(90, 40, 91, 20))
        self.BaudeRade.setObjectName("BaudeRade")
        self.BaudeRade.addItem("")
        self.BaudeRade.addItem("")
        self.timeOut = QtWidgets.QDoubleSpinBox(self.frame_4)
        self.timeOut.setGeometry(QtCore.QRect(70, 60, 91, 21))
        self.timeOut.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.timeOut.setObjectName("timeOut")
        self.frame_5 = QtWidgets.QFrame(Segunda)
        self.frame_5.setGeometry(QtCore.QRect(290, 190, 141, 101))
        self.frame_5.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_15 = QtWidgets.QLabel(self.frame_5)
        self.label_15.setGeometry(QtCore.QRect(30, 0, 91, 20))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame_5)
        self.label_16.setGeometry(QtCore.QRect(0, 30, 81, 16))
        self.label_16.setObjectName("label_16")
        self.samplerate = QtWidgets.QLineEdit(self.frame_5)
        self.samplerate.setGeometry(QtCore.QRect(80, 30, 51, 23))
        self.samplerate.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.samplerate.setObjectName("samplerate")
        self.label_17 = QtWidgets.QLabel(self.frame_5)
        self.label_17.setGeometry(QtCore.QRect(0, 60, 101, 16))
        self.label_17.setObjectName("label_17")
        self.samplinperiod = QtWidgets.QDoubleSpinBox(self.frame_5)
        self.samplinperiod.setGeometry(QtCore.QRect(90, 60, 51, 20))
        self.samplinperiod.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.samplinperiod.setObjectName("samplinperiod")
        self.frame_6 = QtWidgets.QFrame(Segunda)
        self.frame_6.setGeometry(QtCore.QRect(440, 190, 111, 101))
        self.frame_6.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_18 = QtWidgets.QLabel(self.frame_6)
        self.label_18.setGeometry(QtCore.QRect(20, 0, 71, 20))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.frame_6)
        self.label_19.setGeometry(QtCore.QRect(0, 20, 71, 20))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.frame_6)
        self.label_20.setGeometry(QtCore.QRect(0, 40, 71, 20))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.frame_6)
        self.label_21.setGeometry(QtCore.QRect(0, 60, 71, 20))
        self.label_21.setObjectName("label_21")
        self.filename = QtWidgets.QSpinBox(self.frame_6)
        self.filename.setGeometry(QtCore.QRect(60, 20, 41, 21))
        self.filename.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.filename.setObjectName("filename")
        self.extension = QtWidgets.QSpinBox(self.frame_6)
        self.extension.setGeometry(QtCore.QRect(70, 40, 41, 21))
        self.extension.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.extension.setObjectName("extension")
        self.average = QtWidgets.QSpinBox(self.frame_6)
        self.average.setGeometry(QtCore.QRect(60, 60, 41, 21))
        self.average.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.average.setObjectName("average")

        self.retranslateUi(Segunda)
        self.buttonBox.accepted.connect(Segunda.accept)
        self.buttonBox.rejected.connect(Segunda.reject)
        QtCore.QMetaObject.connectSlotsByName(Segunda)

    def retranslateUi(self, Segunda):
        _translate = QtCore.QCoreApplication.translate
        Segunda.setWindowTitle(_translate("Segunda", "Dialog"))
        self.label.setText(_translate("Segunda", "<html><head/><body><p><span style=\" font-weight:600;\">Brand:</span> Lakeshore</p></body></html>"))
        self.label_2.setText(_translate("Segunda", "<html><head/><body><p><span style=\" font-weight:600;\">Model: </span>DT-670</p></body></html>"))
        self.label_3.setText(_translate("Segunda", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Equipment</span></p></body></html>"))
        self.sensor1.setText(_translate("Segunda", "Sensor 1"))
        self.sensor2.setText(_translate("Segunda", "Sensor 2"))
        self.sensor3.setText(_translate("Segunda", "Sensor 3"))
        self.sensor4.setText(_translate("Segunda", "Sensor 4"))
        self.sensor5.setText(_translate("Segunda", "Sensor 5"))
        self.sensor6.setText(_translate("Segunda", "Sensor 6"))
        self.sensor1_type.setItemText(0, _translate("Segunda", "2.5v Diode"))
        self.sensor1_type.setItemText(1, _translate("Segunda", "Cernox"))
        self.sensor2_type.setItemText(0, _translate("Segunda", "2.5v Diode"))
        self.sensor2_type.setItemText(1, _translate("Segunda", "Cernox"))
        self.sensor3_type.setItemText(0, _translate("Segunda", "2.5v Diode"))
        self.sensor3_type.setItemText(1, _translate("Segunda", "Cernox"))
        self.sensor4_type.setItemText(0, _translate("Segunda", "2.5v Diode"))
        self.sensor4_type.setItemText(1, _translate("Segunda", "Cernox"))
        self.sesnor5_type.setItemText(0, _translate("Segunda", "2.5v Diode"))
        self.sesnor5_type.setItemText(1, _translate("Segunda", "Cernox"))
        self.sensor6_type.setItemText(0, _translate("Segunda", "2.5v Diode"))
        self.sensor6_type.setItemText(1, _translate("Segunda", "Cernox"))
        self.sensor7_type.setItemText(0, _translate("Segunda", "2.5v Diode"))
        self.sensor7_type.setItemText(1, _translate("Segunda", "Cernox"))
        self.sensor8_type.setItemText(0, _translate("Segunda", "2.5v Diode"))
        self.sensor8_type.setItemText(1, _translate("Segunda", "Cernox"))
        self.label_4.setText(_translate("Segunda", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt; font-weight:600;\">TypeSensors</span></p></body></html>"))
        self.sensor7.setText(_translate("Segunda", "Sensor 7"))
        self.sensor8.setText(_translate("Segunda", "Sensor 8"))
        self.label_13.setText(_translate("Segunda", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Curve</span></p></body></html>"))
        self.label_5.setText(_translate("Segunda", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">File</span></p></body></html>"))
        self.label_6.setText(_translate("Segunda", "Root:"))
        self.label_7.setText(_translate("Segunda", "Name:"))
        self.label_8.setText(_translate("Segunda", "SaveData:"))
        self.root.setText(_translate("Segunda", "/home/detectores/Experiments/PruebaCalefactorCCD/"))
        self.name.setText(_translate("Segunda", "Sensores_218.txt"))
        self.label_10.setText(_translate("Segunda", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Communication parameters</span></p></body></html>"))
        self.label_9.setText(_translate("Segunda", "Port:"))
        self.label_11.setText(_translate("Segunda", "BaudeRade:"))
        self.label_12.setText(_translate("Segunda", "TimeOut:"))
        self.port.setText(_translate("Segunda", "/dev/ttyUSB1"))
        self.BaudeRade.setItemText(0, _translate("Segunda", "9600"))
        self.BaudeRade.setItemText(1, _translate("Segunda", "57600"))
        self.label_15.setText(_translate("Segunda", "<html><head/><body><p><span style=\" font-weight:600;\">Acquisition</span></p></body></html>"))
        self.label_16.setText(_translate("Segunda", "SampleRate:"))
        self.samplerate.setText(_translate("Segunda", "none"))
        self.label_17.setText(_translate("Segunda", "SamplinPeriod:"))
        self.label_18.setText(_translate("Segunda", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Storage</span></p><p align=\"center\"><br/></p></body></html>"))
        self.label_19.setText(_translate("Segunda", "FileName:"))
        self.label_20.setText(_translate("Segunda", "Extension:"))
        self.label_21.setText(_translate("Segunda", "Average:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Segunda = QtWidgets.QDialog()
    ui = Ui_Segunda()
    ui.setupUi(Segunda)
    Segunda.show()
    sys.exit(app.exec_())

