# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'segunda.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Segunda(object):
    def setupUi(self, Segunda):
        Segunda.setObjectName("Segunda")
        Segunda.resize(706, 395)
        self.buttonBox = QtWidgets.QDialogButtonBox(Segunda)
        self.buttonBox.setGeometry(QtCore.QRect(110, 330, 541, 41))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.frame = QtWidgets.QFrame(Segunda)
        self.frame.setGeometry(QtCore.QRect(10, 20, 171, 81))
        self.frame.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 12pt \"Sans Serif\";")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 19, 151, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 131, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 171, 20))
        self.label_3.setObjectName("label_3")
        self.label_3.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.frame_2 = QtWidgets.QFrame(Segunda)
        self.frame_2.setGeometry(QtCore.QRect(10, 110, 391, 201))
        self.frame_2.setStyleSheet("background-color: rgb(85, 255, 0);\n"
"font: 12pt \"Sans Serif\";")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.sensor1 = QtWidgets.QCheckBox(self.frame_2)
        self.sensor1.setGeometry(QtCore.QRect(20, 30, 91, 21))
        self.sensor1.setChecked(True)
        self.sensor1.setObjectName("sensor1")
        self.sensor2 = QtWidgets.QCheckBox(self.frame_2)
        self.sensor2.setGeometry(QtCore.QRect(20, 50, 99, 21))
        self.sensor2.setChecked(True)
        self.sensor2.setObjectName("sensor2")
        self.sensor3 = QtWidgets.QCheckBox(self.frame_2)
        self.sensor3.setGeometry(QtCore.QRect(20, 70, 99, 21))
        self.sensor3.setChecked(True)
        self.sensor3.setObjectName("sensor3")
        self.sensor4 = QtWidgets.QCheckBox(self.frame_2)
        self.sensor4.setGeometry(QtCore.QRect(20, 90, 99, 21))
        self.sensor4.setChecked(True)
        self.sensor4.setObjectName("sensor4")
        self.sensor5 = QtWidgets.QCheckBox(self.frame_2)
        self.sensor5.setGeometry(QtCore.QRect(20, 110, 99, 21))
        self.sensor5.setChecked(True)
        self.sensor5.setObjectName("sensor5")
        self.sensor6 = QtWidgets.QCheckBox(self.frame_2)
        self.sensor6.setGeometry(QtCore.QRect(20, 130, 99, 21))
        self.sensor6.setChecked(True)
        self.sensor6.setObjectName("sensor6")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(160, 10, 131, 20))
        self.label_4.setObjectName("label_4")
        self.sensor7 = QtWidgets.QCheckBox(self.frame_2)
        self.sensor7.setGeometry(QtCore.QRect(20, 150, 99, 21))
        self.sensor7.setObjectName("sensor7")
        self.sensor8 = QtWidgets.QCheckBox(self.frame_2)
        self.sensor8.setGeometry(QtCore.QRect(20, 170, 99, 21))
        self.sensor8.setObjectName("sensor8")
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setGeometry(QtCore.QRect(320, 10, 61, 16))
        self.label_13.setObjectName("label_13")
        self.spinBox = QtWidgets.QSpinBox(self.frame_2)
        self.spinBox.setGeometry(QtCore.QRect(330, 30, 47, 21))
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(self.frame_2)
        self.spinBox_2.setGeometry(QtCore.QRect(330, 50, 47, 24))
        self.spinBox_2.setObjectName("spinBox_2")
        self.spinBox_3 = QtWidgets.QSpinBox(self.frame_2)
        self.spinBox_3.setGeometry(QtCore.QRect(330, 70, 47, 24))
        self.spinBox_3.setObjectName("spinBox_3")
        self.spinBox_4 = QtWidgets.QSpinBox(self.frame_2)
        self.spinBox_4.setGeometry(QtCore.QRect(330, 90, 47, 24))
        self.spinBox_4.setObjectName("spinBox_4")
        self.spinBox_5 = QtWidgets.QSpinBox(self.frame_2)
        self.spinBox_5.setGeometry(QtCore.QRect(330, 110, 47, 24))
        self.spinBox_5.setObjectName("spinBox_5")
        self.spinBox_6 = QtWidgets.QSpinBox(self.frame_2)
        self.spinBox_6.setGeometry(QtCore.QRect(330, 130, 47, 24))
        self.spinBox_6.setObjectName("spinBox_6")
        self.spinBox_7 = QtWidgets.QSpinBox(self.frame_2)
        self.spinBox_7.setEnabled(False)
        self.spinBox_7.setGeometry(QtCore.QRect(330, 150, 47, 24))
        self.spinBox_7.setObjectName("spinBox_7")
        self.spinBox_8 = QtWidgets.QSpinBox(self.frame_2)
        self.spinBox_8.setEnabled(False)
        self.spinBox_8.setGeometry(QtCore.QRect(330, 170, 47, 24))
        self.spinBox_8.setObjectName("spinBox_8")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setGeometry(QtCore.QRect(120, 30, 201, 23))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"Sans Serif\";")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 50, 201, 23))
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"Sans Serif\";")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(120, 70, 201, 23))
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"Sans Serif\";")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(120, 90, 201, 23))
        self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"Sans Serif\";")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(120, 110, 201, 23))
        self.lineEdit_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"Sans Serif\";\n"
"")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(120, 130, 201, 23))
        self.lineEdit_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"Sans Serif\";")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_7.setEnabled(False)
        self.lineEdit_7.setGeometry(QtCore.QRect(120, 150, 201, 23))
        self.lineEdit_7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"Sans Serif\";")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_8.setEnabled(False)
        self.lineEdit_8.setGeometry(QtCore.QRect(120, 170, 201, 23))
        self.lineEdit_8.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"Sans Serif\";")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.sensor1.raise_()
        self.sensor8.raise_()
        self.sensor7.raise_()
        self.sensor6.raise_()
        self.sensor5.raise_()
        self.sensor4.raise_()
        self.sensor3.raise_()
        self.sensor2.raise_()
        self.label_4.raise_()
        self.label_13.raise_()
        self.spinBox.raise_()
        self.spinBox_2.raise_()
        self.spinBox_3.raise_()
        self.spinBox_4.raise_()
        self.spinBox_5.raise_()
        self.spinBox_6.raise_()
        self.spinBox_7.raise_()
        self.spinBox_8.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_3.raise_()
        self.lineEdit_4.raise_()
        self.lineEdit_5.raise_()
        self.lineEdit_6.raise_()
        self.lineEdit_7.raise_()
        self.lineEdit_8.raise_()
        self.frame_3 = QtWidgets.QFrame(Segunda)
        self.frame_3.setGeometry(QtCore.QRect(190, 20, 501, 81))
        self.frame_3.setStyleSheet("background-color: rgb(85, 170, 0);\n"
"font: 12pt \"Sans Serif\";")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 461, 20))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(20, 20, 51, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(320, 20, 81, 16))
        self.label_8.setObjectName("label_8")
        self.name = QtWidgets.QLineEdit(self.frame_3)
        self.name.setGeometry(QtCore.QRect(80, 20, 231, 21))
        self.name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.name.setObjectName("name")
        self.savedata = QtWidgets.QSpinBox(self.frame_3)
        self.savedata.setGeometry(QtCore.QRect(410, 20, 61, 20))
        self.savedata.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.savedata.setObjectName("savedata")
        self.label_14 = QtWidgets.QLabel(self.frame_3)
        self.label_14.setGeometry(QtCore.QRect(20, 50, 121, 16))
        self.label_14.setObjectName("label_14")
        self.name_2 = QtWidgets.QLineEdit(self.frame_3)
        self.name_2.setGeometry(QtCore.QRect(150, 50, 321, 21))
        self.name_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.name_2.setObjectName("name_2")
        self.frame_4 = QtWidgets.QFrame(Segunda)
        self.frame_4.setGeometry(QtCore.QRect(410, 190, 281, 121))
        self.frame_4.setStyleSheet("background-color: rgb(85, 170, 127);\n"
"font: 12pt \"Sans Serif\";")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_10 = QtWidgets.QLabel(self.frame_4)
        self.label_10.setGeometry(QtCore.QRect(0, 0, 291, 16))
        self.label_10.setObjectName("label_10")
        self.label_9 = QtWidgets.QLabel(self.frame_4)
        self.label_9.setGeometry(QtCore.QRect(20, 30, 61, 21))
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.frame_4)
        self.label_11.setGeometry(QtCore.QRect(20, 60, 211, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame_4)
        self.label_12.setGeometry(QtCore.QRect(20, 90, 81, 16))
        self.label_12.setObjectName("label_12")
        self.port = QtWidgets.QLineEdit(self.frame_4)
        self.port.setGeometry(QtCore.QRect(60, 30, 211, 21))
        self.port.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.port.setObjectName("port")
        self.timeOut = QtWidgets.QDoubleSpinBox(self.frame_4)
        self.timeOut.setGeometry(QtCore.QRect(100, 90, 61, 21))
        self.timeOut.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.timeOut.setObjectName("timeOut")
        self.frame_5 = QtWidgets.QFrame(Segunda)
        self.frame_5.setGeometry(QtCore.QRect(190, 320, 211, 61))
        self.frame_5.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"font: 12pt \"Sans Serif\";")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_15 = QtWidgets.QLabel(self.frame_5)
        self.label_15.setGeometry(QtCore.QRect(0, 0, 201, 21))
        self.label_15.setObjectName("label_15")
        self.label_17 = QtWidgets.QLabel(self.frame_5)
        self.label_17.setGeometry(QtCore.QRect(10, 30, 121, 16))
        self.label_17.setObjectName("label_17")
        self.samplinperiod = QtWidgets.QDoubleSpinBox(self.frame_5)
        self.samplinperiod.setGeometry(QtCore.QRect(140, 29, 61, 21))
        self.samplinperiod.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.samplinperiod.setObjectName("samplinperiod")
        self.frame_6 = QtWidgets.QFrame(Segunda)
        self.frame_6.setGeometry(QtCore.QRect(10, 320, 171, 61))
        self.frame_6.setStyleSheet("background-color: rgb(0, 0, 255);\n"
"font: 12pt \"Sans Serif\";")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_18 = QtWidgets.QLabel(self.frame_6)
        self.label_18.setGeometry(QtCore.QRect(0, 0, 171, 20))
        self.label_18.setObjectName("label_18")
        self.label_21 = QtWidgets.QLabel(self.frame_6)
        self.label_21.setGeometry(QtCore.QRect(10, 30, 81, 21))
        self.label_21.setObjectName("label_21")
        self.average = QtWidgets.QSpinBox(self.frame_6)
        self.average.setGeometry(QtCore.QRect(90, 30, 61, 21))
        self.average.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.average.setObjectName("average")
        self.frame_7 = QtWidgets.QFrame(Segunda)
        self.frame_7.setGeometry(QtCore.QRect(410, 110, 281, 71))
        self.frame_7.setStyleSheet("background-color: rgb(0, 255, 127);\n"
"font: 12pt \"Sans Serif\";")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_16 = QtWidgets.QLabel(self.frame_7)
        self.label_16.setGeometry(QtCore.QRect(10, 40, 71, 21))
        self.label_16.setObjectName("label_16")
        self.label_19 = QtWidgets.QLabel(self.frame_7)
        self.label_19.setGeometry(QtCore.QRect(0, 10, 281, 20))
        self.label_19.setObjectName("label_19")
        self.port_2 = QtWidgets.QLineEdit(self.frame_7)
        self.port_2.setGeometry(QtCore.QRect(70, 40, 201, 21))
        self.port_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"Sans Serif\";")
        self.port_2.setObjectName("port_2")

        self.retranslateUi(Segunda)
        self.buttonBox.accepted.connect(Segunda.accept)
        self.buttonBox.rejected.connect(Segunda.reject)
        QtCore.QMetaObject.connectSlotsByName(Segunda)

    def retranslateUi(self, Segunda):
        _translate = QtCore.QCoreApplication.translate
        Segunda.setWindowTitle(_translate("Segunda", "Dialog"))
        self.label.setText(_translate("Segunda", "<html><head/><body><p><span style=\" font-weight:600;\">Brand:</span> Lakeshore</p></body></html>"))
        self.label_2.setText(_translate("Segunda", "<html><head/><body><p><span style=\" font-weight:600;\">Model: </span>218</p></body></html>"))
        self.label_3.setText(_translate("Segunda", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Equipment</span></p></body></html>"))
        self.sensor1.setText(_translate("Segunda", "Sensor 1"))
        self.sensor2.setText(_translate("Segunda", "Sensor 2"))
        self.sensor3.setText(_translate("Segunda", "Sensor 3"))
        self.sensor4.setText(_translate("Segunda", "Sensor 4"))
        self.sensor5.setText(_translate("Segunda", "Sensor 5"))
        self.sensor6.setText(_translate("Segunda", "Sensor 6"))
        self.label_4.setText(_translate("Segunda", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">TypeSensors</span></p></body></html>"))
        self.sensor7.setText(_translate("Segunda", "Sensor 7"))
        self.sensor8.setText(_translate("Segunda", "Sensor 8"))
        self.label_13.setText(_translate("Segunda", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Curve</span></p></body></html>"))
        self.lineEdit.setText(_translate("Segunda", "Diodo"))
        self.lineEdit_2.setText(_translate("Segunda", "Diodo"))
        self.lineEdit_3.setText(_translate("Segunda", "Diodo"))
        self.lineEdit_4.setText(_translate("Segunda", "Diodo"))
        self.lineEdit_5.setText(_translate("Segunda", "Cernox"))
        self.lineEdit_6.setText(_translate("Segunda", "Cernox"))
        self.label_5.setText(_translate("Segunda", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">File</span></p></body></html>"))
        self.label_7.setText(_translate("Segunda", "Name:"))
        self.label_8.setText(_translate("Segunda", "SaveData:"))
        self.name.setText(_translate("Segunda", "Sensores_218.txt"))
        self.label_14.setText(_translate("Segunda", "NameAverage:"))
        self.name_2.setText(_translate("Segunda", "Sensores_Average_218.txt"))
        self.label_10.setText(_translate("Segunda", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Communication parameters</span></p></body></html>"))
        self.label_9.setText(_translate("Segunda", "Port:"))
        self.label_11.setText(_translate("Segunda", "BaudeRade: 9600"))
        self.label_12.setText(_translate("Segunda", "TimeOut:"))
        self.port.setText(_translate("Segunda", "/dev/ttyUSB1"))
        self.label_15.setText(_translate("Segunda", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Acquisition</span></p></body></html>"))
        self.label_17.setText(_translate("Segunda", "SamplinPeriod:"))
        self.label_18.setText(_translate("Segunda", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Storage</span></p></body></html>"))
        self.label_21.setText(_translate("Segunda", "<html><head/><body><p align=\"center\">Average:</p></body></html>"))
        self.label_16.setText(_translate("Segunda", "Model:"))
        self.label_19.setText(_translate("Segunda", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">About sensors</span></p></body></html>"))
        self.port_2.setText(_translate("Segunda", "1-4: DT-670 ; 5-6: Cernox"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Segunda = QtWidgets.QDialog()
    ui = Ui_Segunda()
    ui.setupUi(Segunda)
    Segunda.show()
    sys.exit(app.exec_())

