# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tercera.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Tercera(object):
    def setupUi(self, Tercera):
        Tercera.setObjectName("Tercera")
        Tercera.resize(703, 348)
        self.buttonBox = QtWidgets.QDialogButtonBox(Tercera)
        self.buttonBox.setGeometry(QtCore.QRect(220, 310, 461, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.frame_5 = QtWidgets.QFrame(Tercera)
        self.frame_5.setGeometry(QtCore.QRect(190, 230, 211, 71))
        self.frame_5.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"font: 12pt \"Sans Serif\";")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_54 = QtWidgets.QLabel(self.frame_5)
        self.label_54.setGeometry(QtCore.QRect(0, 0, 211, 31))
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.frame_5)
        self.label_55.setGeometry(QtCore.QRect(10, 40, 121, 16))
        self.label_55.setObjectName("label_55")
        self.samplinperiod_3 = QtWidgets.QDoubleSpinBox(self.frame_5)
        self.samplinperiod_3.setGeometry(QtCore.QRect(140, 40, 61, 21))
        self.samplinperiod_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.samplinperiod_3.setObjectName("samplinperiod_3")
        self.frame_6 = QtWidgets.QFrame(Tercera)
        self.frame_6.setGeometry(QtCore.QRect(10, 230, 171, 71))
        self.frame_6.setStyleSheet("background-color: rgb(0, 0, 255);\n"
"font: 12pt \"Sans Serif\";")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_52 = QtWidgets.QLabel(self.frame_6)
        self.label_52.setGeometry(QtCore.QRect(0, 0, 171, 31))
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.frame_6)
        self.label_53.setGeometry(QtCore.QRect(10, 40, 81, 21))
        self.label_53.setObjectName("label_53")
        self.average_3 = QtWidgets.QSpinBox(self.frame_6)
        self.average_3.setGeometry(QtCore.QRect(100, 40, 61, 21))
        self.average_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.average_3.setObjectName("average_3")
        self.frame_2 = QtWidgets.QFrame(Tercera)
        self.frame_2.setGeometry(QtCore.QRect(10, 110, 391, 111))
        self.frame_2.setStyleSheet("background-color: rgb(85, 255, 0);\n"
"font: 12pt \"Sans Serif\";")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.sensor1_3 = QtWidgets.QCheckBox(self.frame_2)
        self.sensor1_3.setGeometry(QtCore.QRect(20, 40, 91, 21))
        self.sensor1_3.setChecked(True)
        self.sensor1_3.setObjectName("sensor1_3")
        self.sensor2_3 = QtWidgets.QCheckBox(self.frame_2)
        self.sensor2_3.setGeometry(QtCore.QRect(20, 70, 99, 21))
        self.sensor2_3.setChecked(True)
        self.sensor2_3.setObjectName("sensor2_3")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(160, 10, 131, 20))
        self.label_7.setObjectName("label_7")
        self.label_21 = QtWidgets.QLabel(self.frame_2)
        self.label_21.setGeometry(QtCore.QRect(320, 10, 61, 16))
        self.label_21.setObjectName("label_21")
        self.spinBox_11 = QtWidgets.QSpinBox(self.frame_2)
        self.spinBox_11.setGeometry(QtCore.QRect(330, 40, 47, 21))
        self.spinBox_11.setObjectName("spinBox_11")
        self.spinBox_12 = QtWidgets.QSpinBox(self.frame_2)
        self.spinBox_12.setGeometry(QtCore.QRect(330, 70, 47, 24))
        self.spinBox_12.setObjectName("spinBox_12")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_11.setGeometry(QtCore.QRect(120, 40, 201, 23))
        self.lineEdit_11.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"Sans Serif\";")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_12.setGeometry(QtCore.QRect(120, 70, 201, 23))
        self.lineEdit_12.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"Sans Serif\";")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.frame = QtWidgets.QFrame(Tercera)
        self.frame.setGeometry(QtCore.QRect(10, 20, 171, 81))
        self.frame.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 12pt \"Sans Serif\";")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_49 = QtWidgets.QLabel(self.frame)
        self.label_49.setGeometry(QtCore.QRect(10, 19, 151, 31))
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.frame)
        self.label_50.setGeometry(QtCore.QRect(10, 50, 131, 20))
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.frame)
        self.label_51.setGeometry(QtCore.QRect(0, 0, 171, 20))
        self.label_51.setObjectName("label_51")
        self.frame_3 = QtWidgets.QFrame(Tercera)
        self.frame_3.setGeometry(QtCore.QRect(190, 20, 501, 81))
        self.frame_3.setStyleSheet("background-color: rgb(85, 170, 0);\n"
"font: 12pt \"Sans Serif\";")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_45 = QtWidgets.QLabel(self.frame_3)
        self.label_45.setGeometry(QtCore.QRect(0, 0, 461, 20))
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.frame_3)
        self.label_46.setGeometry(QtCore.QRect(20, 20, 51, 16))
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.frame_3)
        self.label_47.setGeometry(QtCore.QRect(320, 20, 81, 16))
        self.label_47.setObjectName("label_47")
        self.name_5 = QtWidgets.QLineEdit(self.frame_3)
        self.name_5.setGeometry(QtCore.QRect(80, 20, 231, 21))
        self.name_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.name_5.setObjectName("name_5")
        self.savedata_3 = QtWidgets.QSpinBox(self.frame_3)
        self.savedata_3.setGeometry(QtCore.QRect(410, 20, 61, 20))
        self.savedata_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.savedata_3.setObjectName("savedata_3")
        self.label_48 = QtWidgets.QLabel(self.frame_3)
        self.label_48.setGeometry(QtCore.QRect(20, 50, 121, 16))
        self.label_48.setObjectName("label_48")
        self.name_6 = QtWidgets.QLineEdit(self.frame_3)
        self.name_6.setGeometry(QtCore.QRect(150, 50, 321, 21))
        self.name_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.name_6.setObjectName("name_6")
        self.frame_7 = QtWidgets.QFrame(Tercera)
        self.frame_7.setGeometry(QtCore.QRect(410, 110, 281, 61))
        self.frame_7.setStyleSheet("background-color: rgb(0, 255, 127);\n"
"font: 12pt \"Sans Serif\";")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_39 = QtWidgets.QLabel(self.frame_7)
        self.label_39.setGeometry(QtCore.QRect(10, 30, 71, 21))
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.frame_7)
        self.label_40.setGeometry(QtCore.QRect(0, 10, 281, 20))
        self.label_40.setObjectName("label_40")
        self.port_5 = QtWidgets.QLineEdit(self.frame_7)
        self.port_5.setGeometry(QtCore.QRect(70, 30, 201, 21))
        self.port_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"Sans Serif\";")
        self.port_5.setObjectName("port_5")
        self.frame_4 = QtWidgets.QFrame(Tercera)
        self.frame_4.setGeometry(QtCore.QRect(410, 180, 281, 121))
        self.frame_4.setStyleSheet("background-color: rgb(85, 170, 127);\n"
"font: 12pt \"Sans Serif\";")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_41 = QtWidgets.QLabel(self.frame_4)
        self.label_41.setGeometry(QtCore.QRect(0, 0, 291, 31))
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.frame_4)
        self.label_42.setGeometry(QtCore.QRect(20, 30, 61, 21))
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.frame_4)
        self.label_43.setGeometry(QtCore.QRect(20, 60, 211, 21))
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.frame_4)
        self.label_44.setGeometry(QtCore.QRect(20, 90, 81, 16))
        self.label_44.setObjectName("label_44")
        self.port_6 = QtWidgets.QLineEdit(self.frame_4)
        self.port_6.setGeometry(QtCore.QRect(60, 30, 211, 21))
        self.port_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.port_6.setObjectName("port_6")
        self.timeOut_3 = QtWidgets.QDoubleSpinBox(self.frame_4)
        self.timeOut_3.setGeometry(QtCore.QRect(100, 90, 61, 21))
        self.timeOut_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.timeOut_3.setObjectName("timeOut_3")

        self.retranslateUi(Tercera)
        self.buttonBox.accepted.connect(Tercera.accept)
        self.buttonBox.rejected.connect(Tercera.reject)
        QtCore.QMetaObject.connectSlotsByName(Tercera)

    def retranslateUi(self, Tercera):
        _translate = QtCore.QCoreApplication.translate
        Tercera.setWindowTitle(_translate("Tercera", "Dialog"))
        self.label_54.setText(_translate("Tercera", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Acquisition</span></p></body></html>"))
        self.label_55.setText(_translate("Tercera", "SamplinPeriod:"))
        self.label_52.setText(_translate("Tercera", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Storage</span></p></body></html>"))
        self.label_53.setText(_translate("Tercera", "<html><head/><body><p align=\"center\">Average:</p></body></html>"))
        self.sensor1_3.setText(_translate("Tercera", "Sensor 1"))
        self.sensor2_3.setText(_translate("Tercera", "Sensor 2"))
        self.label_7.setText(_translate("Tercera", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">TypeSensors</span></p></body></html>"))
        self.label_21.setText(_translate("Tercera", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Curve</span></p></body></html>"))
        self.lineEdit_11.setText(_translate("Tercera", "Diodo"))
        self.lineEdit_12.setText(_translate("Tercera", "Diodo"))
        self.label_49.setText(_translate("Tercera", "<html><head/><body><p><span style=\" font-weight:600;\">Brand:</span> Lakeshore</p></body></html>"))
        self.label_50.setText(_translate("Tercera", "<html><head/><body><p><span style=\" font-weight:600;\">Model: 335</span></p></body></html>"))
        self.label_51.setText(_translate("Tercera", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Equipment</span></p></body></html>"))
        self.label_45.setText(_translate("Tercera", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">File</span></p></body></html>"))
        self.label_46.setText(_translate("Tercera", "Name:"))
        self.label_47.setText(_translate("Tercera", "SaveData:"))
        self.name_5.setText(_translate("Tercera", "Sensores_M335.txt"))
        self.label_48.setText(_translate("Tercera", "NameAverage:"))
        self.name_6.setText(_translate("Tercera", "Sensores_Average_M335.txt"))
        self.label_39.setText(_translate("Tercera", "Model:"))
        self.label_40.setText(_translate("Tercera", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">About sensors</span></p></body></html>"))
        self.port_5.setText(_translate("Tercera", "1-2: Cernox"))
        self.label_41.setText(_translate("Tercera", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Communication parameters</span></p></body></html>"))
        self.label_42.setText(_translate("Tercera", "Port:"))
        self.label_43.setText(_translate("Tercera", "BaudeRade: 57600"))
        self.label_44.setText(_translate("Tercera", "TimeOut:"))
        self.port_6.setText(_translate("Tercera", "/dev/ttyUSB0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Tercera = QtWidgets.QDialog()
    ui = Ui_Tercera()
    ui.setupUi(Tercera)
    Tercera.show()
    sys.exit(app.exec_())

