# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tercera.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Tercera(object):
    def setupUi(self, Tercera):
        Tercera.setObjectName("Tercera")
        Tercera.resize(702, 345)
        self.frame_2 = QtWidgets.QFrame(Tercera)
        self.frame_2.setGeometry(QtCore.QRect(10, 100, 391, 111))
        self.frame_2.setStyleSheet("background-color: rgb(85, 255, 0);\n"
"font: 12pt \"Sans Serif\";")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.sensor1_2 = QtWidgets.QCheckBox(self.frame_2)
        self.sensor1_2.setGeometry(QtCore.QRect(20, 40, 91, 21))
        self.sensor1_2.setChecked(True)
        self.sensor1_2.setObjectName("sensor1_2")
        self.sensor2_2 = QtWidgets.QCheckBox(self.frame_2)
        self.sensor2_2.setGeometry(QtCore.QRect(20, 70, 99, 21))
        self.sensor2_2.setChecked(True)
        self.sensor2_2.setObjectName("sensor2_2")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(160, 10, 131, 20))
        self.label_6.setObjectName("label_6")
        self.label_20 = QtWidgets.QLabel(self.frame_2)
        self.label_20.setGeometry(QtCore.QRect(320, 10, 61, 16))
        self.label_20.setObjectName("label_20")
        self.spinBox_9 = QtWidgets.QSpinBox(self.frame_2)
        self.spinBox_9.setGeometry(QtCore.QRect(330, 40, 47, 21))
        self.spinBox_9.setObjectName("spinBox_9")
        self.spinBox_10 = QtWidgets.QSpinBox(self.frame_2)
        self.spinBox_10.setGeometry(QtCore.QRect(330, 70, 47, 24))
        self.spinBox_10.setObjectName("spinBox_10")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_9.setGeometry(QtCore.QRect(120, 40, 201, 23))
        self.lineEdit_9.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"Sans Serif\";")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_10.setGeometry(QtCore.QRect(120, 70, 201, 23))
        self.lineEdit_10.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"Sans Serif\";")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.frame_7 = QtWidgets.QFrame(Tercera)
        self.frame_7.setGeometry(QtCore.QRect(410, 100, 281, 61))
        self.frame_7.setStyleSheet("background-color: rgb(0, 255, 127);\n"
"font: 12pt \"Sans Serif\";")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_22 = QtWidgets.QLabel(self.frame_7)
        self.label_22.setGeometry(QtCore.QRect(10, 30, 71, 21))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.frame_7)
        self.label_23.setGeometry(QtCore.QRect(0, 10, 281, 20))
        self.label_23.setObjectName("label_23")
        self.port_3 = QtWidgets.QLineEdit(self.frame_7)
        self.port_3.setGeometry(QtCore.QRect(70, 30, 201, 21))
        self.port_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"Sans Serif\";")
        self.port_3.setObjectName("port_3")
        self.frame_3 = QtWidgets.QFrame(Tercera)
        self.frame_3.setGeometry(QtCore.QRect(190, 10, 501, 81))
        self.frame_3.setStyleSheet("background-color: rgb(85, 170, 0);\n"
"font: 12pt \"Sans Serif\";")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_24 = QtWidgets.QLabel(self.frame_3)
        self.label_24.setGeometry(QtCore.QRect(0, 0, 461, 20))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.frame_3)
        self.label_25.setGeometry(QtCore.QRect(20, 20, 51, 16))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.frame_3)
        self.label_26.setGeometry(QtCore.QRect(320, 20, 81, 16))
        self.label_26.setObjectName("label_26")
        self.name_3 = QtWidgets.QLineEdit(self.frame_3)
        self.name_3.setGeometry(QtCore.QRect(80, 20, 231, 21))
        self.name_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.name_3.setObjectName("name_3")
        self.savedata_2 = QtWidgets.QSpinBox(self.frame_3)
        self.savedata_2.setGeometry(QtCore.QRect(410, 20, 61, 20))
        self.savedata_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.savedata_2.setObjectName("savedata_2")
        self.label_27 = QtWidgets.QLabel(self.frame_3)
        self.label_27.setGeometry(QtCore.QRect(20, 50, 121, 16))
        self.label_27.setObjectName("label_27")
        self.name_4 = QtWidgets.QLineEdit(self.frame_3)
        self.name_4.setGeometry(QtCore.QRect(150, 50, 321, 21))
        self.name_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.name_4.setObjectName("name_4")
        self.frame_4 = QtWidgets.QFrame(Tercera)
        self.frame_4.setGeometry(QtCore.QRect(410, 170, 281, 121))
        self.frame_4.setStyleSheet("background-color: rgb(85, 170, 127);\n"
"font: 12pt \"Sans Serif\";")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_28 = QtWidgets.QLabel(self.frame_4)
        self.label_28.setGeometry(QtCore.QRect(0, 0, 291, 31))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.frame_4)
        self.label_29.setGeometry(QtCore.QRect(20, 30, 61, 21))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.frame_4)
        self.label_30.setGeometry(QtCore.QRect(20, 60, 211, 21))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.frame_4)
        self.label_31.setGeometry(QtCore.QRect(20, 90, 81, 16))
        self.label_31.setObjectName("label_31")
        self.port_4 = QtWidgets.QLineEdit(self.frame_4)
        self.port_4.setGeometry(QtCore.QRect(60, 30, 211, 21))
        self.port_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.port_4.setObjectName("port_4")
        self.timeOut_2 = QtWidgets.QDoubleSpinBox(self.frame_4)
        self.timeOut_2.setGeometry(QtCore.QRect(100, 90, 61, 21))
        self.timeOut_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.timeOut_2.setObjectName("timeOut_2")
        self.frame_5 = QtWidgets.QFrame(Tercera)
        self.frame_5.setGeometry(QtCore.QRect(190, 220, 211, 71))
        self.frame_5.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"font: 12pt \"Sans Serif\";")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_32 = QtWidgets.QLabel(self.frame_5)
        self.label_32.setGeometry(QtCore.QRect(0, 0, 211, 31))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.frame_5)
        self.label_33.setGeometry(QtCore.QRect(10, 40, 121, 16))
        self.label_33.setObjectName("label_33")
        self.samplinperiod_2 = QtWidgets.QDoubleSpinBox(self.frame_5)
        self.samplinperiod_2.setGeometry(QtCore.QRect(140, 40, 61, 21))
        self.samplinperiod_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.samplinperiod_2.setObjectName("samplinperiod_2")
        self.buttonBox_2 = QtWidgets.QDialogButtonBox(Tercera)
        self.buttonBox_2.setGeometry(QtCore.QRect(140, 300, 541, 41))
        self.buttonBox_2.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox_2.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_2.setObjectName("buttonBox_2")
        self.frame_6 = QtWidgets.QFrame(Tercera)
        self.frame_6.setGeometry(QtCore.QRect(10, 220, 171, 71))
        self.frame_6.setStyleSheet("background-color: rgb(0, 0, 255);\n"
"font: 12pt \"Sans Serif\";")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_34 = QtWidgets.QLabel(self.frame_6)
        self.label_34.setGeometry(QtCore.QRect(0, 0, 171, 31))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.frame_6)
        self.label_35.setGeometry(QtCore.QRect(10, 40, 81, 21))
        self.label_35.setObjectName("label_35")
        self.average_2 = QtWidgets.QSpinBox(self.frame_6)
        self.average_2.setGeometry(QtCore.QRect(100, 40, 61, 21))
        self.average_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.average_2.setObjectName("average_2")
        self.frame = QtWidgets.QFrame(Tercera)
        self.frame.setGeometry(QtCore.QRect(10, 10, 171, 81))
        self.frame.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 12pt \"Sans Serif\";")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_36 = QtWidgets.QLabel(self.frame)
        self.label_36.setGeometry(QtCore.QRect(10, 19, 151, 31))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.frame)
        self.label_37.setGeometry(QtCore.QRect(10, 50, 131, 20))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.frame)
        self.label_38.setGeometry(QtCore.QRect(0, 0, 171, 20))
        self.label_38.setObjectName("label_38")

        self.retranslateUi(Tercera)
        QtCore.QMetaObject.connectSlotsByName(Tercera)

    def retranslateUi(self, Tercera):
        _translate = QtCore.QCoreApplication.translate
        Tercera.setWindowTitle(_translate("Tercera", "Dialog"))
        self.sensor1_2.setText(_translate("Tercera", "Sensor 1"))
        self.sensor2_2.setText(_translate("Tercera", "Sensor 2"))
        self.label_6.setText(_translate("Tercera", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">TypeSensors</span></p></body></html>"))
        self.label_20.setText(_translate("Tercera", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Curve</span></p></body></html>"))
        self.lineEdit_9.setText(_translate("Tercera", "Diodo"))
        self.lineEdit_10.setText(_translate("Tercera", "Diodo"))
        self.label_22.setText(_translate("Tercera", "Model:"))
        self.label_23.setText(_translate("Tercera", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">About sensors</span></p></body></html>"))
        self.port_3.setText(_translate("Tercera", "1-2: Cernox"))
        self.label_24.setText(_translate("Tercera", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">File</span></p></body></html>"))
        self.label_25.setText(_translate("Tercera", "Name:"))
        self.label_26.setText(_translate("Tercera", "SaveData:"))
        self.name_3.setText(_translate("Tercera", "Sensores_M335.txt"))
        self.label_27.setText(_translate("Tercera", "NameAverage:"))
        self.name_4.setText(_translate("Tercera", "Sensores_Average_M335.txt"))
        self.label_28.setText(_translate("Tercera", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Communication parameters</span></p></body></html>"))
        self.label_29.setText(_translate("Tercera", "Port:"))
        self.label_30.setText(_translate("Tercera", "BaudeRade: 57600"))
        self.label_31.setText(_translate("Tercera", "TimeOut:"))
        self.port_4.setText(_translate("Tercera", "/dev/ttyUSB0"))
        self.label_32.setText(_translate("Tercera", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Acquisition</span></p></body></html>"))
        self.label_33.setText(_translate("Tercera", "SamplinPeriod:"))
        self.label_34.setText(_translate("Tercera", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Storage</span></p></body></html>"))
        self.label_35.setText(_translate("Tercera", "<html><head/><body><p align=\"center\">Average:</p></body></html>"))
        self.label_36.setText(_translate("Tercera", "<html><head/><body><p><span style=\" font-weight:600;\">Brand:</span> Lakeshore</p></body></html>"))
        self.label_37.setText(_translate("Tercera", "<html><head/><body><p><span style=\" font-weight:600;\">Model: 335</span></p></body></html>"))
        self.label_38.setText(_translate("Tercera", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Equipment</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Tercera = QtWidgets.QDialog()
    ui = Ui_Tercera()
    ui.setupUi(Tercera)
    Tercera.show()
    sys.exit(app.exec_())

